### ISSUE TITLE
Temporal coverage: error message misplaced/replicated

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#100]
Even if the error is only caused by one of the intervals, the error is reported in each interval:

![image](https://user-images.githubusercontent.com/717359/33940154-40b2dbae-e00e-11e7-89e9-bc67f3b4cf20.png)

**Comment by cezio** [comment]
I can move errors above temp cov block. Error messages don't have any reference to specific item in multiple values, so it's rather hard to match to specific row.

**Comment by etj** [comment]
Ok, let's have the error message on the whole temporal coverages block.

**Comment by cezio** [comment]
i've restyled error for that field a bit:

![image](https://user-images.githubusercontent.com/116021/34209110-30096416-e591-11e7-8876-5d6d3c5afad9.png)

when new temporal coverage period is added, it won't have error styling:
![image](https://user-images.githubusercontent.com/116021/34209142-4c88f638-e591-11e7-91bc-f1739f1c49c7.png)
