### ISSUE TITLE
Travis: run tests against CKAN 2.5, 2.6, 2.7

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#101]
At the moment only CKAN 2.5 is tested.

**Comment by etj** [comment]
Testing on master, 2.7,2.6,2.5,2.4

master and 2.4 are currently failing:
  https://travis-ci.org/etj/ckanext-dcatapit/builds/319796229

**Comment by etj** [comment]
Test branch is https://github.com/etj/ckanext-dcatapit/tree/101_multi_ckan

**Comment by cezio** [comment]
after talk with @etj i've removed master branch from the build matrix for the moment.
