### ISSUE TITLE
conformsTo: _ref field 

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#117]
The `package_show` call will return a `_ref` field in the `conforms_to` bundle.
When harvesting, it's populated with the URI of the `Standard` node, in order to preserve this info when serializing back the dataset. Local datasets do not have such field.

- [x] rename the `_ref` field to `uri` for a better description of its value
- [x] do not include the field in the output when it's blank

**Comment by cezio** [comment]
`_ref`/`uri` can come from rdf, and can be just a bnode value. should we detect this and skip it, accept only correct URIs?
