### ISSUE TITLE
Geographical coverage review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#123]
Improve the geonames field to make the user able to search the desired result instead of having a simple freetext input.

The needed documentation for the geonames web-service can be found [here](http://www.geonames.org/export/), so the user will be able to:

- search by location name 
- a list of possible results appear (if this is the case)
- the dataset field will be filled with the URL of the selected geoname (eg. http://www.geonames.org/3181912)

**Comment by etj** [comment]
- `dct:spatial (0..N) `
  - `locn_geographicalName (0..1)`: To be used only if no URI is available
  - `locn:geometry (0..1)`: extent related to the dataset
  -  `dcatapit:geographicalIdentifier (0..1)`: this is the recommended field to use. It may contain:
     - URI from the controlled voc http://publications.europa.eu/mdr/authority/place/ (recommended)
     - if no URI from the controlled voc is found, a GeoNames URI can be used instead.

**Comment by cezio** [comment]
Should the search be limited to IT, or to any location? Alternatively, we could add configuration param to control which countries should be searched.

**Comment by tdipisa** [comment]
@cezio since this extension have to support an italian standard we could limit the search to the Italy location. However, at the moment, I don't see any particular reason to add this limitation because in some use cases could be useful to set other locations outside Italy, @etj what do you think?

**Comment by cezio** [comment]
I think i could add autocomplete based on http://tompi.github.io/jeoquery/

* some configuration needs to be provided in config (`geonames.username`, `geonames.countries`)
* if we want to use local copy, then we should probably add mit license text there. or we could use hosted (cdn from google) version.

**Comment by cezio** [comment]
I've added jeoquery and needed jqueryui plugins to repo. 

Current UI for setting geonames url:

![image](https://user-images.githubusercontent.com/116021/34949697-22b2577a-fa11-11e7-9e1c-15a47f7f2ff1.png)

I had to add additional field for url, because input receives place description from geonames. Internally, url is set to hidden input.

**Comment by etj** [comment]
- `geonames.limits.countries` doesnt work and makes the js page loading fail
-  it should be still possible to edit the URL directly
