### ISSUE TITLE
Inconsistency in License handling

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#129]
- referring bad var `_name`
https://github.com/geosolutions-it/ckanext-dcatapit/blob/4ed73d8639141e1b4e3b4c6befd56e8ed964ab93/ckanext/dcatapit/interfaces.py#L300

**Comment by cezio** [comment]
Fixed in #86, https://github.com/cezio/ckanext-dcatapit/commit/0c6fa6adbc9ba808b75004c27c72c60d0875bcff#diff-2da5a9880435f3b83e2eaf0feb57be18L300
