### ISSUE TITLE
DCT license type searched in bad node

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#130]
Should search in license node, not distribution:

https://github.com/geosolutions-it/ckanext-dcatapit/blob/75b4b9d8920d3c5293fbb1000d8d7025881eb917/ckanext/dcatapit/dcat/profiles.py#L300

**Comment by cezio** [comment]
fixed in #86, https://github.com/cezio/ckanext-dcatapit/commit/0c6fa6adbc9ba808b75004c27c72c60d0875bcff#diff-bb04760576be278fb234b0c28aaf7a3cL302
