### ISSUE TITLE
before_index is defined twice

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#139]
one of the two will not be called:

https://github.com/geosolutions-it/ckanext-dcatapit/blob/15ee6559591f586331182e0ce30611e8302cbee0/ckanext/dcatapit/plugin.py#L291
https://github.com/geosolutions-it/ckanext-dcatapit/blob/15ee6559591f586331182e0ce30611e8302cbee0/ckanext/dcatapit/plugin.py#L404

**Comment by cezio** [comment]
Merged both implementations, with small improvement to avoid duplicated org fetching.
