### ISSUE TITLE
Review of the assigned ORG

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#156]
Each harvest source should have a proper organization assigned. Currently in test server we have 'Organizzaione Test' that collect harvested dataset from different Harvest Sources. This requires to:

- [x] change the json in the docker config to properly init org and sources.
- [x] change configuration in [test server](http://dcatapit.geo-solutions.it)

**Comment by etj** [comment]
We'll also change the json in the docker config to properly init org and sources.

**Comment by etj** [comment]
Configuration updated in test server.

**Comment by etj** [comment]
Test needed for
https://github.com/geosolutions-it/dati-ckan-docker/issues/16
