### ISSUE TITLE
Harvesting from Regione Toscana

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#157]
We need to perform again the harvest test for the following harvest source since the previous issues should be fixed now in the remote catalog:

- Regione Toscana: http://dati.toscana.it/catalog.rdf

**Comment by etj** [comment]
![ckan101](https://user-images.githubusercontent.com/717359/37039013-ae26f31c-2156-11e8-8801-a0e0b8ba9fc4.png)

Since publisher is 0..1, the errors related to the publisher name and publisher id should be investigated.

**Comment by cezio** [comment]
part of this should be fixed with #163

**Comment by cezio** [comment]
Guys, please check if fixes from #163 removes those errors. Also, is this overlaps with #150?

**Comment by etj** [comment]
@cezio no overlaps. #155 refers to new sources not previously harvested.

**Comment by etj** [comment]
New harvesting results:

![jobreport](https://user-images.githubusercontent.com/717359/37702841-1c78cd88-2cf4-11e8-89b9-d410f8cfb6a7.png)

**Comment by etj** [comment]
Blocked by
- #168 
- #169

**Comment by etj** [comment]
The only remaining errors are caused by bad dataset content:

![toscana](https://user-images.githubusercontent.com/717359/37958028-ad654190-31af-11e8-939b-2fba70b2c847.png)

**Comment by etj** [comment]
The only errors are caused by bad source datasets:

![toscana](https://user-images.githubusercontent.com/717359/37958081-d0875852-31af-11e8-996e-9f61efdee717.png)
