### ISSUE TITLE
Hervest list link in home

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#160]
Add the following page linked in home menu.

http://dcatapit.geo-solutions.it/harvest/list

**Comment by etj** [comment]
Won't it be better to have the link in the footer of the page? 
It's not of general interest usually.

**Comment by giorgialodi** [comment]
Currently in dati.gov.it the list is avaialble within an informative page that describes how to be harvested by the national catalogue. Therefore, probably it makes sense what you are suggesting @etj. In the national catalogue we will find out a way to better valorize that page which makes more sense for users. The idea was to make it visible somehow: at the moment a user should know the link

**Comment by cezio** [comment]
Added

![image](https://user-images.githubusercontent.com/116021/37311676-80a612a0-2648-11e8-9b58-7a9fb246fb76.png)
