### ISSUE TITLE
New Facet for Rights Holder

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#161]
Add a new facet to make the user able to search dataset by rights holder.

**Comment by tdipisa** [comment]
@giorgialodi, I think we need to discuss this issue further.

**Comment by giorgialodi** [comment]
@tdipisa ok I guess that from your investigation it emerged something we need to deal with, right? :-) Let us discuss it in call and continue here also for everybody, if necessary.

**Comment by tdipisa** [comment]
@giorgialodi I just need to describe you what we can do before starting the development to be sure if this fits your needs.
