### ISSUE TITLE
Hide Rights holder in dataset create form

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#162]
During the dataset creation form the Ckan's web-form the rights holder conresponds to the selected organization.
So we should avoid  showing an empty and read-only **Name** and **IPA/IVA code** and put there a placeholder instead to inform the user that an organization must be selected to specify the rights holder, something like the following:

![titolare.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fc9d8e2c8e82bb8aabf301b44fff9e2c4533317346f6727284ba2bbb172f0309581caa41585d41afaa892ca0b72e6c981e5ab38532022d8c6853beb2901eb70bbb25894d85b1ba8a4dc3e83b23f5c6.png)

In dataset read and edit stages we can maintain the current rights holder visualization:

![titolare_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fc9d8e2c8e82bb8ad6ed01e81fe086264c22703d46f96925dce129e6417f545b0d18ab135e5f44fefcda78a6b13a71984019af80330b2b9b645bf9fa9015ad00b22a8a4a87b4bc8d4ac0ea3825e3889d02.png)

@giorgialodi do you agree with the solution above?

**Comment by giorgialodi** [comment]
@tdipisa not very clear to me. "Titolare : Seleziona organizzazione" where is located? in the bottom? Is the standard CKAN one? Ok for the visualization in read stage. In the editing staging do you mean in the web form?

**Comment by tdipisa** [comment]
@giorgialodi now in dataset create form we have the following:

![screen1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fb978826878df8cda5fd53b652fa912a5265296b51fa2971dce02cea167907580d48ac415a5a17aff98e2da7a42062c80d55b98e30063e937f03a6aa801db500bf22894e80b2bd824ac7ea3837aa.png)

Then we will have something like the following:

![screen2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fb978826878dfbcda5fd53b652fa912a5265296b51fa2971dce02cea167907580d48ac415a5a17aff98e2da7a42062c80d55b98e30063e937f03a6aa8317b500bf22894e80b2bf8344c4ef3537aa.png)

We can obviously refine the string content but in any case we have the helper tooltip. As we discussed in the meeting, this represents a GUI update for the Web-Form but just in dataset create form.

**Comment by giorgialodi** [comment]
@tdipisa ok fine but we can improve the text to support better the user. We can add something like " E' l'organizzazione (o pubblica amministrazione) che detiene la titolarità de dati ovvero quella che ha originariamente formato per uso proprio o commissionato ad altro soggetto pubblico o privato il dato. E' necessario selezionare un'organizzazione già esistente presso la piattaforma CKAN. Se l'organizzazione titolare non esiste, è necessario crearla fornendo la sua denominazione e l'identificativo, quest'ultimo rappresentato dal codice IPA (o codice fiscale in caso di organizzazione privata)."

**Comment by tdipisa** [comment]
@giorgialodi we need to distinguish between two cases:

1) the user is working (creating or editing) on a dataset created by the web-form - in this case the helper you suggested is fine

2) the dataset is an harvested dataset - in this case the helper should be changed as follow:

"E' l'organizzazione (o pubblica amministrazione) che detiene la titolarità del dato ovvero quella che ha originariamente formato per uso proprio o commissionato ad altro soggetto pubblico o privato il dato."

**Comment by cezio** [comment]
> the dataset is an harvested dataset - in this case the helper should be changed as follow: "E' l'organizzazione (o pubblica amministrazione) che detiene la titolarità del dato ovvero quella che ha originariamente formato per uso proprio o commissionato ad altro soggetto pubblico o privato il dato."
Just removing the last part

Is this a text for tooltip, or text instead of holder data fields in create form? Harvested datasets can be just updated, they don't have create form.

**Comment by cezio** [comment]
New dataset:

![image](https://user-images.githubusercontent.com/116021/38103410-916a0d9e-3386-11e8-888a-7ec8b84366b8.png)

Editing existing:
![image](https://user-images.githubusercontent.com/116021/38103806-a82c0f18-3387-11e8-94db-3d9b243eb99b.png)

**Comment by giorgialodi** [comment]
@tdipisa but if the dataset is harvested, I can only visualize the metadata without any online helper. I thought that the online helper is necessary only in your fist case. Am I wrong?

**Comment by giorgialodi** [comment]
@cezio in the screenshot:Remove the last period "E' l'organizzazione...." Keep just the first 10 lines of text.
