### ISSUE TITLE
Changed licences and territorial controlled vocabularies

### ISSUE THREAD

**Issue by giorgialodi** [geosolutions-it/ckanext-dcatapit#165]
It is necessary to update two controlled vocabularies: 
1) licences available at: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/licences
2) territorial classification available at: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/territorial-classification

The territorial classification may be subject to additional changes in the upcoming months.
Therefore, it is also necessary to understand how to deal, in a smart way, with possible changes in the vocabularies. 

See also https://github.com/italia/dati-ckan-docker/issues/19

**Comment by etj** [comment]
About territorial classification, there's only a change in a namespace's URI. 

Licenses file has changes a lot: ...

**Comment by etj** [comment]
Licenses have changed once again.
Protocol is now `https`.

**Comment by tdipisa** [comment]
@etj so do we need to move back this issue in ready again to provide more updates?
