### ISSUE TITLE
Publisher should be optional

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#169]
publisher cardinality is 0..1

It should have been fixed as part of #163, but it isn't

https://github.com/geosolutions-it/ckanext-dcatapit/blob/74fa3a0009ceb7af6392b28ac8bf44c53f10e836/ckanext/dcatapit/schema.py#L154

and harvesters will generate this kind of error:

```
Create validation Error: {'Publisher identifier': 'Missing value', 'Publisher name': 'Missing value'}
```

**Comment by cezio** [comment]
Indeed. Sorry, I've missed this somehow in previous issue (probably due to switching between branches).
