### ISSUE TITLE
New Harvesting Tests (Round 2)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#177]
New Harvest sources must be tested:

- Regione Lazio (CKAN without DCAT-AP_IT)
- Provincia Autonoma di Bolzano (via RDF - CKAN with DCAT-AP_IT)
- Comune di Bari (CKAN without DCAT-AP_IT)
- Città metropolitana di Roma Capitale (DCAT JSON) (waiting for the RDF endpoint)
- Regione Emilia Romagna (via RDF - CKAN with DCAT-AP_IT)
- Provincia Autonoma di Trento (via RDF - CKAN with DCAT-AP_IT)
- Regione Lombardia (via RDF - DCAT-AP_IT) (they are currently fixing the content-type issue, so wait testing this)

For current status and errors details refer to:
https://docs.google.com/spreadsheets/d/1RhTOpO1VJTDvn8LdEYCnMvP6Fim21mNANR9D-f7Dkzs/edit#gid=0

**Comment by etj** [comment]
Also
- [ ] create orgs
- [ ] create json files for new orgs
- [ ] create json files for new sources

**Comment by etj** [comment]
- Regione Lazio: 
   `'https://dati.lazio.it/api/3/action/package_search?sort=id+asc&start=0&rows=100'. Error: HTTP error: 404`

**Comment by giorgialodi** [comment]
@etj Probably they change the URL because they have the English and Italian version of the catalog. I am just searching the right URL

**Comment by giorgialodi** [comment]
@etj it could be https://dati.lazio.it/catalog (not sure with final "/" or not)

**Comment by giorgialodi** [comment]
@etj @tdipisa just to inform you that also Lombardia should be fine now.

**Comment by giorgialodi** [comment]
@etj @tdipisa in the gdrive file I can see that in the case of Regione Sardegna the datasets are 388 with 0 errors. However the Region has 619 datasets. What happened in that case?

**Comment by giorgialodi** [comment]
in any case Regione Sardegna exposes at the time being (it was not like that in the past) the catalog.rdf http://dati.regione.sardegna.it/catalog.rdf Probably we can try that

**Comment by etj** [comment]
@giorgialodi Regione Sardegna returns 620 datasets indeed. Should have been a typo. When you find something strange, please also refer to http://agid.geo-solutions.it/harvest/list to check the real values.

**Comment by giorgialodi** [comment]
@etj thank you! I am going to check it. Just a question: to this link http://dcatapit.geo-solutions.it/dataset I can see the last imported datasets, right? In the case of MIUR, I see just 30 datasets but in the list you pointed out above there are many others. Am I wrong?

**Comment by etj** [comment]
@giorgialodi Fixes have been applied to the instance http://agid.geo-solutions.it, so you can see the actual harvested dataset numbers here: http://agid.geo-solutions.it/harvest/list

**Comment by giorgialodi** [comment]
@tdipisa @etj  Pronincia Autonoma di Trento sent the error logs: they will correct the errors we observed  from the session of harvesting soon (probably within tomorrow). I will include here the status of this activitity for the other PAs as well I am contacting.

**Comment by giorgialodi** [comment]
@tdipisa @etj Toscana sent the error logs. Waiting for a reply.
