### ISSUE TITLE
New Harvesting Tests (Round 3)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#184]
New Harvest sources must be tested (sources URL can be found [here](https://docs.google.com/spreadsheets/d/1bShW5SiGf3ByUa3bst2USSaXQOtgRSWaCHXWIJRnCcI/edit#gid=191595306)):

- [x] Regione Marche (CKAN senza DCAT-AP_IT. dataset 27)
- [x] Regione Puglia (CKAN senza DCAT-AP_IT. dataset 111)
- [x] Regione Siciliana (CKAN con DCAT-AP_IT. dataset 21)

- [x] Comune di Lecce (CKAN con DCAT-AP_IT. 437 dataset)
- [x] Comune di Matera (CKAN con DCAT-AP_IT. 186 dataset)
- [x] Provincia di Asti (CKAN senza DCAT-AP_IT; 243 dataset)
- [x] Comune di Reggio Calabria (CKAN senza DCAT-AP_IT. 160 dataset)
- [x] Comune di Genova (DCAT JSON. 118 dataset)
- [x] Comune di Francavilla Fontana (CKAN con DCAT-AP_IT. Hanno 119 dataset)

**optionals:** 
- [ ] Catalogo Federato Salento Jionico (Regione Puglia. Hanno 52 dataset)
- [ ] Città metropolitana Napoli (CKAN con DCAT-AP_IT. dataset 12)
- [ ] Comune di Galatone (CKAN con DCAT-AP_IT. Hanno 38 dataset)
- [ ] Terre della Gravina (CKAN con DCAT-AP_IT. Hanno 28 dataset)

For current status and errors details refer to:
https://docs.google.com/spreadsheets/d/1RhTOpO1VJTDvn8LdEYCnMvP6Fim21mNANR9D-f7Dkzs/edit#gid=0

**Comment by etj** [comment]
Comune di Lecce non sembra avere dcatapit installato

**Comment by giorgialodi** [comment]
@etj esatto lecce non è dcatapit al momento se ricordo bene. Si deve andare via CKAN-CKAN normale.
