### ISSUE TITLE
Editing form glitches

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#190]
- [x] when the section tab is selected, it's white and turns blue only when focus is lost
- [x] tooltip bkg is transparent,but should be opaque
- [x] rightsholder info is always displayed in the bottom of the form:
   ![titedit1](https://user-images.githubusercontent.com/717359/38681941-36a78910-3e6a-11e8-90e2-eb5f3a470cdc.png)
   This only happnes on dataset creation, and not in dataset update.
- [ ] i18n review [@etj]
- [x] Some fields are misaligned (both in dataset creation form and editign form)
![clipboard02](https://user-images.githubusercontent.com/1280027/38928764-85a20ece-430a-11e8-97f2-52fe2b8022b9.png)

- [x] Some labels are missing for remove buttons
![screen 2](https://user-images.githubusercontent.com/1280027/38928529-69a4c50a-4309-11e8-8caa-593bc7d3428c.png)

- [x] **Related databases** should be **Related Datasets**
![clipboard07](https://user-images.githubusercontent.com/1280027/38928741-6bac32d8-430a-11e8-9cc9-4f9b1af37d31.png)

- [x] When saving an existing dataset with multilang tags we have the following error:
```
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/default.py', line 435 in do_execute
  cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) null value in column "lang" violates not-null constraint
DETAIL:  Failing row contains (10, 1b96d7a3-7481-40f4-af52-838c7f143322, test, null, test).
 'INSERT INTO tag_multilang (tag_id, tag_name, lang, text) VALUES (%(tag_id)s, %(tag_name)s, %(lang)s, %(text)s) RETURNING tag_multilang.id' {'lang': None, 'text': u'test', 'tag_name': u'test', 'tag_id': u'1b96d7a3-7481-40f4-af52-838c7f143322'}
```
- [x] The label **Add new Theme** is not correct if there aren't theme by default
![clipboard09](https://user-images.githubusercontent.com/1280027/38928427-1af96460-4309-11e8-987f-09a86744a04e.png)

just change the label to **Add a Theme**
  
- [x] The look and feel of the NAV menu must be reviewed:
![clipboard010](https://user-images.githubusercontent.com/1280027/38928619-b61f44f0-4309-11e8-9856-0e6ac2e20556.png)

**Comment by cezio** [comment]
> The look and feel of the NAV menu must be reviewed:

Could you provide more specific description of the problem?

**Comment by tdipisa** [comment]
@cezio An idea could be something like [this](https://bootsnipp.com/snippets/featured/simple-vertical-tab)

![clipboard01112](https://user-images.githubusercontent.com/1280027/39526240-7eef789a-4e1e-11e8-8870-e724f34446c9.png)

or simply accommodate the look and feel that we have in the home for the facets:
![clipboard0111](https://user-images.githubusercontent.com/1280027/39526198-5cfde690-4e1e-11e8-9833-2dc0430ed326.png)

**Comment by tdipisa** [comment]
@cezio Can you try to fix this please?

**Comment by cezio** [comment]
Form layout improvements:

 * menu items are using full width of sidebar, they resemble more facet menus

 * layout of customized form fields is more standardized:
  * add new widgets are aligned to the same position
  * remove widgets contain label 
  * removable elements are visually distinct with thin border

![image](https://user-images.githubusercontent.com/116021/39634631-96fe881a-4fbb-11e8-82a5-c510a2f33d77.png)

![image](https://user-images.githubusercontent.com/116021/39634645-a30f738a-4fbb-11e8-822e-f23c14198990.png)

![image](https://user-images.githubusercontent.com/116021/39634662-af49f7ce-4fbb-11e8-893f-ff9d4233ae36.png)

![image](https://user-images.githubusercontent.com/116021/39634689-bc6b642e-4fbb-11e8-9f94-64bc38e94f69.png)

**Comment by tdipisa** [comment]
@cezio, instead of using the following to remove an object:

![clipboard01223345](https://user-images.githubusercontent.com/1280027/39637098-56e79616-4fc2-11e8-9a2a-8d973a1cd8bc.png)

Can we replace it with a button like the following?

![clipboard0123](https://user-images.githubusercontent.com/1280027/39637053-3bf14d5c-4fc2-11e8-8b07-65e231d2c909.png)
This may solves some space issues in my opinion and could be more easy to manage, what do you think? In this way we stay faithful to the Ckan's base L&F.

**Comment by cezio** [comment]
> When saving an existing dataset with multilang tags we have the following error:

This is because both extensions provide `templates/package/snippets/package_basic_fields.html` file, which customizes package form.

**Comment by cezio** [comment]
> @cezio, instead of using the following to remove an object:

![image](https://user-images.githubusercontent.com/116021/39640816-81825b5e-4fcc-11e8-8874-6b836c6563bd.png)

![image](https://user-images.githubusercontent.com/116021/39640829-8e33a2d6-4fcc-11e8-93b3-9d968cf40a3d.png)

**Comment by cezio** [comment]
https://github.com/geosolutions-it/ckanext-dcatapit/issues/190#issuecomment-386643630

For the record, one way to solve this is to have `package_basic_fields.html` templates in both extensions. 
Each of them should extend blocks from ml one (`package_basic_fields_tags` and `package_basic_fields_org`), include contents of those blocks with ignore missing:

```
{% include "may_or_may_not_exists.html" ignore missing %}

```.

if only multilang is in use, nothing changes. if dcatapit is in use, it will try to include templates from ml and fail silently if files are not available.

However, multilang extension provides several other template customizations (especially it replaces default pkg_dict with localized values). Maybe some of them may be moved to `IPackageController.before_view()`.

**Comment by cezio** [comment]
> When saving an existing dataset with multilang tags we have the following error:

should be fixed with https://github.com/geosolutions-it/ckanext-multilang/pull/16

**Comment by cezio** [comment]
Per request from @tdipisa I've added `ckanext.dcatapit.form_tabs` config var which controls if edit form is rendered with tabs or not. Default is: tabs are enabled.
