### ISSUE TITLE
Exception in _update_pkg_rights_holder's stack: organization_show did not call its auth function

### ISSUE THREAD

**Issue by AndreaFinazzi** [geosolutions-it/ckanext-dcatapit#202]
I'm facing an issue which seems to came out every time the requests load grows over a certain level (for instance under multiple package_create or http stress tests):
ckan handles without problems the earlier requests, but begins to throw an **Exception** after a while. 

Debugging didn't help, stepping through rows one at a time doesn't reproduce the issue.
The __auth_audit machine works when requests came one by  one, but under stress something fails.

I've temporarily 'switched off' the method [_update_pkg_rights_holder](https://github.com/geosolutions-it/ckanext-dcatapit/blob/6a86b3f8cb7364a56933e5212d83ebfc3ef818ef/ckanext/dcatapit/plugin.py#L446) and everything seems to go for the right way (except for the obviously missing holder fields).

```
 File '/opt/ckan/produzione/src/ckanext-dcatapit/ckanext/dcatapit/plugin.py', line 407 in before_view
   return self._update_pkg_rights_holder(pkg_dict)
 File '/opt/ckan/produzione/src/ckanext-dcatapit/ckanext/dcatapit/plugin.py', line 421 in _update_pkg_rights_holder
   org = get_org(ctx, {'id': pkg_dict['owner_org']})
 File '/opt/ckan/produzione/src/ckan/ckan/logic/__init__.py', line 467 in wrapped
   .format(action_name))
 Exception: Action function organization_show did not call its auth function
```

**Comment by etj** [comment]
A static context is used when the `organization_show` action is called.
The context should be recreated every time and not shared among the various threads.
