### ISSUE TITLE
CKAN 2.6.6 DCATAP_IT errore catalog.rdf

### ISSUE THREAD

**Issue by piersoft** [geosolutions-it/ckanext-dcatapit#218]
Ho dovuto migrare un CKAN 2.1 al 2.6.6. non ho potuto usare il docker.
Qui trovate la macchina http://91.231.179.187/

Ho installato il plugin come tante altre volte. non ho il multilang extension perchè non mi serve.
Non ne vuole sapere di generare il catalog.rdf. Se nel production.ini tolgo il profilo it da ckanext.dcat.rdf.profiles = euro_dcat_ap , il catalog funziona ma ovviamente secondo il DCATAP standard.
Quando metto il DCATAP_IT nel log del CKAN mi trovo solo questo :
WARNI [ckanext.dcatapit.dcat.profiles] No mulitlang source data
[remote 127.0.0.1:49087] Error - <type 'exceptions.TypeError'>: string indices must be integers

non ho la più pallida idea di cosa possa essere. Nelle installazioni docker mai avuto questo tipo di errore. 

Come posso approfondire per capire in che punto il plugin dcatapit va in conflitto con qualcosa?

**Comment by piersoft** [comment]
ho risolto trovando piano piano la parte del codice che non andava. nel profiles.py (in ckanext/dcatapit/dcat)

    897 +             g.add((license, FOAF.name, Literal(resource_dict.get('name'))))
            -             g.add((license, FOAF.name, Literal(n['name'], lang=n['lang'])))

la parte Literal(n['name'], lang=n['lang']) dava errore. l'ho cambiata come sopra ma non so se esiste una soluzione più elegante.

a voi.

**Comment by etj** [comment]
Dovresti usare il codice più recente.

Puoi vedere il fix su questo commit:

https://github.com/geosolutions-it/ckanext-dcatapit/commit/5f1997f8666ca713eae0c0ab4c39b1c0feee9b35#diff-bb04760576be278fb234b0c28aaf7a3cL897
