### ISSUE TITLE
places-skos.rdf provincia mancante

### ISSUE THREAD

**Issue by eslu** [geosolutions-it/ckanext-dcatapit#222]
Salve,
ho notato che nel vocabolario places-skos.rdf manca la provincia di Avellino.

**Comment by tdipisa** [comment]
Salve,
l'estensione fa uso dei vocabolari controllati che sono indicati all'interno delle specifiche dcat_ap-it.
Ad ogni modo nel caso in cui una località risulti mancante nella lista di elementi relativi al campo **copertura geografica** si può utilizzare **URI di GeoNames** come alternativa.

**Comment by giorgialodi** [comment]
Gentile @eslu il vocabolario europeo non copre tutti i vari territori. Confermo pertanto quanto scritto da @tdipisa: qualora il vocabolario europeo non copra tutto, si può usare GeoNames. Questo dicono le specifiche europee DCAT-AP e quindi quelle italiane. Il tool  consente di inserire l'URI di geonames. 
Ciao
Giorgia
