### ISSUE TITLE
License Migration

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#224]
Investigate on the possibilitiy to use the same [logic](https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/harvesters/csw_harvester.py#L319) we used in the CSW harvester to assign the license to dataset resources during the migration.

Moreover, in that piece of code *license_url* and *license* are used as keys but in ckanext-spatial uses *licen**c**e_url* and *licen**c**e* (is there a typo?).

**Comment by cezio** [comment]
> Moreover, in that piece of code license_url and license are used as keys but in ckanext-spatial uses licence_url and licence (is there a typo?).

Technically it's not a typo, licen*s*e is in us-english, licen*c*e is in british english. Code in PR should handle both cases.
