### ISSUE TITLE
problema con web form e menu "soggetti"

### ISSUE THREAD

**Issue by giorgialodi** [geosolutions-it/ckanext-dcatapit#245]
Ciao a tutti (@tdipisa , @etj , @marcomb ),
abbiamo aggiornato su un istanza di test tutti i sottomoduli di ckan-docker (che stanno su developers italia) incluso anche quello che punta all'ultima versione dcat-ap_it (ultimo commit di 7 giorni fa).
Che cos'è successo? Vedo due cose strane:

1) non c'è più la guida per l'inserimento dei metadati. Ovvero tutte le sezioni che comparivano a sinistra quando si aggiungeva un nuovo dataset non ci sono più

2) La dicitura "soggetti" è comparsa anche nel menu a faccette e nel menu in alto. Secondo me la dicitura "soggetti" era da usare SOLO nel web form e non nei vari menu di CKAN che hanno anche una semantica diversa. Mi spiego meglio: CKAN usa organizzazioni come quelle legate alle sorgenti di harvesting. Nel profilo cDCAT-AP_IT ci sono tanti Soggetti, non solo quelli che pubblicano (e che sono collegati alle sorgenti di harvesting) ma i Titotari (cosa ancora da gestire per bene in termini di harvesting e di filtri e non direttamente collegati alle sorgenti di harvesting) e i creatori dei dataset. Mettendo "soggetti" nei menu di ckan che si usano per altri motivi si crea confusione secondo me perché un utente si aspetta tutte le tipologie di soggetti e non è così in CKAN. 

Secondo me quindi bisogna quanto prima:
1) capire perché è sparita tutta la strutturazione a passi del web form e ripristinarla
2) usare "soggetti" solo nel web form lasciando invariata l'interfaccia di CKAN per tutti gli altri menu. Ai redattori si deve spiegare la differenza e si deve soprattutto spiegare la parte di web form, ignorando il resto che non è ancora pienamente predisposto per poter distinguire bene i vari ruoli dei soggetti che si trovano nel profilo.
3) forse se proprio si vuole cambiare la dicitura dei menu di CKAN cambierei Gruppi in Temi che mi sembra molto più appropriato (e la semantica coincide questa volta perché raggruppiamo - gruppi - i dataset per argomenti, che sono appunto i temi)

Più prima che poi dovremmo sistamare bene al questione titolare, richiesta da tante PA che gestiscono, da aggregatori, cataloghi comunali (tipo Provincia autonoma di Trento, Lombardia, Toscana, Piemonte).

**Comment by tdipisa** [comment]
@giorgialodi 

> 1. capire perché è sparita tutta la strutturazione a passi del web form e ripristinarla

Questa problema non mi risulta, non so quale procedura di aggiornamento avete seguito o che branch state usando. Con gli ultimi due commit di @marcomb sono state aggiornate solamente alcune translations, non sono state introdotte modifiche ai templates. 

> 2. usare "soggetti" solo nel web form lasciando invariata l'interfaccia di CKAN per tutti gli altri menu. Ai redattori si deve spiegare la differenza e si deve soprattutto spiegare la parte di web form, ignorando il resto che non è ancora pienamente predisposto per poter distinguire bene i vari ruoli dei soggetti che si trovano nel profilo.

Ho creato la PR #246 per applicare la dicitura **Soggetti** solamente alla web form, la stessa translation era in effetti usata anche per la Facet delle organizzazioni

**Comment by giorgialodi** [comment]
> @giorgialodi
> 
> > 1. capire perché è sparita tutta la strutturazione a passi del web form e ripristinarla
> 
> Questa problema non mi risulta, non so quale procedura di aggiornamento avete seguito o che branch state usando. Con gli ultimi due commit di @marcomb sono state aggiornate solamente alcune translations, non sono state introdotte modifiche ai templates.

i ragazzi hanno montato su una piattaforma di test il ckan-docker che sta su developers aggiornando tutti i submodules, inclusa l'estensione DCAT-AP_IT. Se faccio aggiungi un dataset questo è quello che vedo:

<img width="1279" alt="Screen Shot 2019-03-26 at 14 51 09" src="https://user-images.githubusercontent.com/24624577/55002695-5be7ed80-4fd7-11e9-94fb-68c9a576397a.png">

Come vedi a sx non vedo i vari passi.

Stiamo usando il branch master per l'estensione. Quale dobbiamo usare, nel caso?

> > 1. usare "soggetti" solo nel web form lasciando invariata l'interfaccia di CKAN per tutti gli altri menu. Ai redattori si deve spiegare la differenza e si deve soprattutto spiegare la parte di web form, ignorando il resto che non è ancora pienamente predisposto per poter distinguire bene i vari ruoli dei soggetti che si trovano nel profilo.
> 
> Ho creato la PR #246 per applicare la dicitura **Soggetti** solamente alla web form, la stessa translation era in effetti usata anche per la Facet delle organizzazioni

Va bene. Procediamo così allora, sperando di riuscire a vedere quel "soggetti" :)

**Comment by tdipisa** [comment]
@giorgialodi 
va bene usare il branch master. La nuova webform è attiva di default ma volendo è possibile disabilitarla, vedi il [readme](https://github.com/geosolutions-it/ckanext-dcatapit#dataset-form). Magari avete quell'opzione di configurazione impostata a false.

Altra cosa che ti avevo accennato già in passato, osservando il tuo screenshot vedo che i campi Copertura Geografica e Lingue del dataset non sono renderizzati correttamente, suppongo che qualche richiesta per il caricamento della form non sia andata a buon fine: avete impostato il site_url?

**Comment by giorgialodi** [comment]
> @giorgialodi
> va bene usare il branch master. La nuova webform è attiva di default ma volendo è possibile disabilitarla, vedi il [readme](https://github.com/geosolutions-it/ckanext-dcatapit#dataset-form). Magari avete quell'opzione di configurazione impostata a _false_.

Ah ok, questo era particolare che a me sfuggiva sicuramente. Lo comunico.

> 
> Altra cosa che ti avevo accennato già in passato, osservando il tuo screenshot vedo che i campi Copertura Geografica e Lingue del dataset non sono renderizzati correttamente, suppongo che qualche richiesta per il caricamento della form non sia andata a buon fine: avete impostato il site_url?

L'avevo detto a suo tempo ma non so se è stato fatto. Ora lo riferisco. Grazie. 

Ti faccio sapere se il primo punto si riesce a vedere o meno

**Comment by giorgialodi** [comment]
@tdipisa il problema che avevamo sulla visualizzazione a sx si è risolto settando il site_url != localhost. Ora abbiamo un altro problema più grande dopo l'aggiornamento di tutti i moduli del ckan docker. Stiamo verificando. Nel caso ti chiederò alcune cose. Grazie per il momento
