### ISSUE TITLE
Obsolete vocabularies

### ISSUE THREAD

**Issue by marcoingrosso** [geosolutions-it/ckanext-dcatapit#248]
Dear contributors,
vocabularies links in the installatione guide are obsolete and no more available.
In addiction, I would need a new version for eurovoc.rdf and eurovoc_mapping.rdf : where can I find them?
Thanks a lot in advance!

**Comment by lucapelizzo** [comment]
I used these:
https://op.europa.eu/it/web/eu-vocabularies/at-dataset/-/resource/dataset/language/
https://op.europa.eu/it/web/eu-vocabularies/at-dataset/-/resource/dataset/data-theme/
https://op.europa.eu/it/web/eu-vocabularies/at-dataset/-/resource/dataset/place/
https://op.europa.eu/it/web/eu-vocabularies/at-dataset/-/resource/dataset/frequency/
https://op.europa.eu/it/web/eu-vocabularies/at-dataset/-/resource/dataset/file-type/

**Comment by marcomb** [comment]
Which vocabulary did you use for theme-subtheme? 
Could you post this  link also? 
Is it this one https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/theme-subtheme-mapping?

**Comment by tdipisa** [comment]
Closed in favor of #274
