### ISSUE TITLE
Documentation fix -> ckanext-multilang required instead of optional

### ISSUE THREAD

**Issue by lucapelizzo** [geosolutions-it/ckanext-dcatapit#251]
The documentation states that ckanext-multilang is optional, but if it's not fully installed (btw it doesn't need to be enabled) I get an error when executing this command: _paster --plugin=ckanext-dcatapit vocabulary initdb_

**Comment by tdipisa** [comment]
Done with https://github.com/geosolutions-it/ckanext-dcatapit/commit/66c4d786a887604bfa9be489b33d0774d907bfcc
