### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by RedsAnDev** [geosolutions-it/ckanext-dcatapit#255]
Hi, thank you for your effort to provide, maintain an develop this plugin.

I'm looking around your documentation and I had a 404 for a link:

```http://www.dati.gov.it/content/dcat-ap_it_v10```

maybe this is the updated version

```https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0```

**Comment by etj** [comment]
Thanks! 
Link updated in the README file.
