### ISSUE TITLE
Check the demo site

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#261]
The README references the demo site http://dcatapit.geo-solutions.it/ that at the moment exists but returns a debiad default page.

**Comment by randomorder** [comment]
The DNS should be pruned or updated. That VM does not exist anymore and the hosting server and IPS don't belong to GeoSolutions anymore

**Comment by randomorder** [comment]
please let me know how you'd like to proceed @etj

**Comment by tdipisa** [comment]
@etj the client shared the dump of the CKAN prod DB. I put it in dropbox [here](https://www.dropbox.com/s/jn4es0e82lr186e/ckan_dump.tgz?dl=0).

**Comment by randomorder** [comment]
I've removed the old DNS record @etj @tdipisa 
I'm going to create internal issues for the setup of the new demo
