### ISSUE TITLE
CKAN 2.10 bug

### ISSUE THREAD

**Issue by piersoft** [geosolutions-it/ckanext-dcatapit#296]
Dopo aver forzato l'installazione adeguando l'estensione per il ckan 2.10, mi sono accorto che lateralmente non vengono calcolati i Temi, Licenze e Sottotemi nella pagina "dataset", come da immagine allegata:

<img width="491" alt="bug210" src="https://github.com/geosolutions-it/ckanext-dcatapit/assets/6083002/af853c98-9c68-4df0-9381-2578aa43c790">

E' capitato ad altri?
Nella pagina "organizzazioni" poi le licenze (sui dataset e non sulle risorse) poi ci sono.

**Comment by piersoft** [comment]
-ho capito il problema 
iRoute non è più usato. Quindi before_map nel plugin.py non viene eseguito. va migrata la funzione a IBlueprint

**Comment by piersoft** [comment]
Partendo da queste [changes](changes/6501.removal) documentate, alla fine si riesce senza stravolgere più di tanto il codice del plugin.py .
<img width="380" alt="Screenshot 2023-08-10 alle 15 37 56" src="https://github.com/geosolutions-it/ckanext-dcatapit/assets/6083002/87235b18-6f40-4691-89ce-e78c83dc3cbd">

**Comment by GenioIdiota** [comment]
Sto avendo problemi nell'installare l'estensione dcatapit con ckan 2.10 (errori del tipo cannot import name 'model' from 'ckan.lib.base').

Nel tuo post hai scritto che hai forzato l'installazione adeguando l'estensione per il ckan 2.10. Che modifiche hai eseguito a dcatapit per adeguarlo a ckan 2.10?

**Comment by piersoft** [comment]
Molte. Se vuoi contattami direttamente. Cosi magari rendiamo strutturali le modifiche e le condividiamo qui con la comunità. Se non cambia l’ip puoi vedere una demo su  http://101.58.87.84/ Non funziona ancora il mapping automatico dei gruppi negli harvesting ma il resto è okPiersoftInviato da iPhoneIl giorno 8 set 2023, alle ore 12:54, GenioIdiota ***@***.***> ha scritto:﻿
Sto avendo problemi nell'installare l'estensione dcatapit con ckan 2.10 (errori del tipo cannot import name 'model' from 'ckan.lib.base').
Nel tuo post hai scritto che hai forzato l'installazione adeguando l'estensione per il ckan 2.10. Che modifiche hai eseguito a dcatapit per adeguarlo a ckan 2.10?

**Comment by ziudeso** [comment]
Idem, @piersoft provato ad installare 2.10 ma stessi errori di @GenioIdiota, saresti cosi' gentile da darci qualche dritta?
Grazie mille 🙏

**Comment by GenioIdiota** [comment]
@ziudeso questa versione di dcatapit non è compatibile con la versione 2.10 di Ckan, alla fine ho installato la 2.9. @piersoft nella sua pagina ha pubblicato una versione di dcatapit con le patch per CKAN 2.10.

**Comment by piersoft** [comment]
Leggete tutto il readme, compreso l'addendum
https://github.com/piersoft/dcatapit_ckan210

**Comment by ziudeso** [comment]
Grazie mille @GenioIdiota, stavo impazzendo, ora provo con quella e ti dico, top!
Grazie anche a te @piersoft per la patch, proverò anche quella!

**Comment by piersoft** [comment]
Ciao a tutti. se volete ho dockerizzato tutto, compreso il dcatapit, con CKAN 2.10.
https://github.com/piersoft/ckan-docker

**Comment by etj** [comment]
As stated in the README, currently this extension is only compatible with CKAN 2.9.
Please follow #300 for any advancement on 2.10 compatibility.
