### ISSUE TITLE
Error in editing legacy orga

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#3]
If you enter in the organization editing page for an orga that existed before adding the dcatapit extension, you get an error.

**Comment by tdipisa** [comment]
This happens because the 'email' field is mandatory for the validation and ckan checks this when the edit form is activated. Solved in [schema configuration](https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/schema.py#L66).
