### ISSUE TITLE
catalog.rdf senza temi, frequenza e spesso rightholders

### ISSUE THREAD

**Issue by piersoft** [geosolutions-it/ckanext-dcatapit#50]
credo che il problema sia in questo file:
ckanext-dcatapit/ckanext/dcatapit/dcat/profiles.py

se voi aprite un link diretto di un dataset del tipo:

http://dati.retecivica.bz.it/it/dataset/servizi-webservice-sasa.rdf

trovate correttamente compliati:
http://publications.europa.eu/resource/authority/data-theme/TRAN
http://publications.europa.eu/resource/authority/frequency/CONT
e il tag <dct:rightsHolder> con foaf:name>SASA S.p.A.</foaf:name>

Ora scaricate:
il http://dati.retecivica.bz.it/it/catalog.rdf
cercando servizi-webservice-sasa troverete gli stessi campi ma con : 
http://publications.europa.eu/resource/authority/data-theme/OP_DATPRO
http://publications.europa.eu/resource/authority/frequency/UNKNOWN
<foaf:name>N/A</foaf:name>

**Comment by piersoft** [comment]
per allargare il campo, lo stesso bug è presente sui portali dove ho usato il vostro plugin, cosi potete investigare a 360°
dati.comune.galatone.le.it
dati.comune.terlizzi.ba.it
dati.comune.francavillafontana.br.it

Nel caso del rights holder per poterlo fare importare su dati.gov.it ho dovuto modificare il codice in modo da produrre in caso di N/A il nome del Comune, ma è un palliativo e sopratuttto non risolve la frequency e il theme.

**Comment by piersoft** [comment]
credo di aver trovato il bug:
1) ckan.locales_offered = it o altra lingua è opportuno che sia compilato
2) la sezione Additional Info (che è con campi liberi) DEVE essere compilata con almeno un valore.

Ho provato su un paio di ckan con pochi dataset e funziona:
dati.matera-basilicata2019.it/catalog.rdf 
e poi in locale.

Non sono capace a mettere una patch che riempie il campo vuoto con un valore di default ma intanto è certo che il bug è qui. 
a voi esperti per la patch :) 
<img width="743" alt="schermata 2017-07-26 alle 09 20 36" src="https://user-images.githubusercontent.com/6083002/28609624-c5fa487a-71e5-11e7-841e-58f7c8319e14.png">

**Comment by marcomb** [comment]
Ciao, ho ripreso in mano la issue, analizzando il catalog.rdf su Dati.Trentino.it. Effettivamente il problema appare sui dataset che non sono stati "adeguati" a DCATAPIT nei loro valori (e non solo quindi tramite l'installazione dell'estensione). Adeguando i metadati, inserendo un campo extra (spesso la facciamo e la lingua) il problema sembra (non è facile testarlo su migliaia di dataset) scomparire. Nel nostro caso si vede chiaramente sui dati statistici che non stiamo adeguando ancora (a livello di valori) a DCATAPIT.

**Comment by piersoft** [comment]
allora Marco è proprio un bug.

Non sempre i campi extra sono compilati. Voi in Trentino lo fate di solito
e quindi il problema è limitato. Ma rimane come bug.

Ho adeguato tutti i portali che gestisco inserendo con un automa un campo
extra generico e il bug scompare.

Andrebbe risolto però a monte .

Anche il Docker di AGID-TeamIT ovviamente risente di tale bug.
p

Il giorno 4 ottobre 2017 10:08, Marco Combetto <notifications@github.com>
ha scritto:

**Comment by marcomb** [comment]
Be, direi che c'è un bug e c'è una feature_by_design.
Il bug è che ci debba essere almeno un campo extra compilato. Lo abbiamo dato per scontato. Non è proprio una cavolata, perchè almeno un campo extra per dire almeno se è manuale e/o harvestato ci sta.

La feature è che è corretto che non basta installare l'estensione e lo schema, ma che i valori vadano "valorizzati". Il tema va assegnato se non è stato assegnato, la lingua va assegnata se non è stata assegnata almeno una, il rightsowner va assegnato, etc..

Comunque ora vediamo come si puo migliorare.. intanto aggiungiamo i sottotemi e miglioriamo la geolocalizzazione collegando il luogo con geonames, in modo da facilitare anche quella compilazione

**Comment by marcomb** [comment]
Quello che non capisco invece è perchè non su alcuni cataloghi (non quelli di BZ, TN) non ci sia il "/catalog-rdf". Pensavo fosse automatica la creazione. @piersoft sui tuoi cataloghi tutti hanno il catalog.rdf? L'Emilia-romagna non ce l'ha, neanche la Sardegna.. e mi risulta usino la stessa estensione..

**Comment by piersoft** [comment]
http://dati.regione.sardegna.it/catalog.rdf  da internal error vuol dire
che hanno configurato male i plugin
vedo che hanno installato di tutto nel catalogo
http://dati.regione.sardegna.it/api/util/status

Emilia romagna: http://dati.emilia-romagna.it/api/util/status
anche qui credo non abbiano configurato bene l'end point perchè nel codice
sorgente trovo:

<link rel="alternate" type="text/n3" href="
http://dati.emilia-romagna.it/catalog.n3"/>
<link rel="alternate" type="text/ttl" href="
http://dati.emilia-romagna.it/catalog.ttl"/>
<link rel="alternate" type="application/rdf+xml" href="
http://dati.emilia-romagna.it/catalog.xml"/>
<link rel="alternate" type="application/ld+json" href="
http://dati.emilia-romagna.it/catalog.jsonld"/>

ma nessun link funziona.

Il giorno 4 ottobre 2017 14:23, Marco Combetto <notifications@github.com>
ha scritto:

**Comment by piersoft** [comment]
eh non è scontato :)

infatti anche il catalogo trentino di bolzano ne è affetto.



Piersoft
Inviato da iPhone

> Il giorno 04 ott 2017, alle ore 14:20, Marco Combetto <notifications@github.com> ha scritto:
> 
> Il bug è che ci debba essere almeno un campo extra compilato. Lo abbiamo dato per scontato

**Comment by etj** [comment]
Should be a duplicate of #51.

Not replicable at the moment.
