### ISSUE TITLE
Handle source Catalog

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#52]
Allow the user to search only for harvested datasets belonging to a given Catalog.

- [x] The GUI will show the "source catalog" facet in the dataset search page.
- [x] The search API will allow a new search key to filter by source catalog.

- PR in official DCAT extension: https://github.com/ckan/ckanext-dcat/pull/101

**Comment by etj** [comment]
= Implementation notes 

We need to add catalog info into the dataset. This is not an info required by DCAT, so a good idea would be to add it as an `extras` field.

We need at least:
- `source_catalog_title`; (main language only?)
- `source_catalog_uri`; (or URL? note we have the landing page for the dataset anyway)

These info needs to be 
- indexed, 
- returned as facets
- shown in the dataset search page

== Populating the info

=== Creating new datasets

asdasd

=== DCAT harvester

adsasd

=== CKAN harvester

asdasd

**Comment by giorgialodi** [comment]
In DCAT-AP_IT (and in DCAT-AP defined at the European level) there are a set of information regarding the catalogue. All PAs that expose an RDF file compliant with DCAT-AP and DCAT-AP_IT must include a class that is dcatapit:Catalog (and thus a dcat:Catalog). The class is mandatory and has some properties related to the catalog (title, homepage, last update, language, etc.). Therefore, that data can be found. See https://linee-guida-cataloghi-dati-profilo-dcat-ap-it.readthedocs.io/it/latest/catalogo.html As far as I understand you want to bring this data into the dataset component of CKAN, right? It is something like having an inverse property connecting the dataset to the catalog (something like isDatasetFor inverse property of dcat:dataset currently used in all RDF files published by PAs). Is this your point?

**Comment by etj** [comment]
@giorgialodi the problem is about transitive harvesting.
Let's say node A and node B are two nodes in which datasets are created
B harvests from A, so B contains datasets created locally, plus datasets created by A.

We then have a node C that harvests B. How can C find out which datasets belong to (i.e. were originally created on) B, and which datasets belong to A? 
If we rely on the Catalog node only, it will seem that ALL datasets belong to catalog B, which isn't the case. So we should associate a new node to the dataset, that tells which is its original source catalog.

**Comment by etj** [comment]
Another solutions is about using the `dct:hasPart` property, which expresses in pure DCAT semantic this requirement.

Let's say 
- Catalog C1 has Datasets D1a D1b
- Catalog C2 has Datasets D2a D2b

C1 exposes a catalog.rdf as:
- Catalog  C1 
  - Dataset D1a     
  - Dataset D1b

C2 harvests from C1.
The related RDF could be expressed as:
- Catalog C2 (URI, title, description, homepage)   
  - Dataset D2a        
  - Dataset D2b     
  - dct:hasPart      
     - Catalog C1 (URI, title, description, homepage)        
       -  Dataset D1a               
       -  Dataset D1b

Since C2 has Datasets nested in inner catalogs, the harvesting and serialization should be reworked a bit; this change would fit much better in ckanext-dcat than in ckanext-dcatapit.

**Comment by giorgialodi** [comment]
@etj I agree that it is likely that having a Catalog node only is not enough. But probably we are saying the same thing. I simply was reasoning on that at the abstraction of DCAT-AP_IT model :) We need to keep track of the relationship between the Catalog and its datasets (this is already available in the RDF-based catalogs), and of the inverse; that is, we need to associate each dataset with the related Catalog. This may also allow us to faciliate in the future the management of duplications of datasets  coming from different Catalogs (geodatasets that are included in both open data catalogs and RNDT). Regarding the dct:hasPart property, I need to check again its semantics and usage in DCAT-AP (and DCAT). I will be back to you again on this.

**Comment by giorgialodi** [comment]
here I am! I checked the property dct:hasPart. The property is not defined in the original DCAT ontology; rather it is an extension introduced in DCAT-AP to capture the situations in which a catalog is part of another (or a catalog includes another one as in your example above). In fact, in DCAT-AP there exist dct:hasPart and its inverse dct:isPartOf. In DCAT-AP_IT we did not include these properties but we can extend the italian profile to include them (almost two years are spent since the release of the Italian extension, and we can consider a revision process to accommodate these issues).  To be more precise, DCAT uses somehow dct:hasPart as subproperty of dcat:dataset. In any case, this latter proposed solution seems to me nice. However,  based on the above observations it does not seem something related to the general DCAT; it is bound to the European application profile, and then to the Italian application profile. Probably it is something to manage in ckanext-dcatapit

**Comment by etj** [comment]
The only complete profile implemented in [ckanext-dcat](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/profiles.py) is the EuropeanDCATAPProfile. So IMHO this is the right place to put the `dct:isPartOf` handling in.

Please also note that, in case the `dct:isPartOf`implementation is done in ckanext-dcatapit,  a DCAT CKAN harvesting a DCATAPIT CKAN would not be able to properly import the datasets belonging to the sub-catalog.

**Comment by cezio** [comment]
PR: https://github.com/geosolutions-it/ckanext-dcat/pull/2

**Comment by etj** [comment]
Cleaner PR in official DCAT repo: https://github.com/ckan/ckanext-dcat/pull/101

**Comment by etj** [comment]
Even if the PR is still under review and has still to be approved, comments are mainly about "style".
In the meanwhile, you can use the code in this branch:
    https://github.com/geosolutions-it/ckanext-dcat/tree/96_source_catalog
