### ISSUE TITLE
Bind Dataset to Groups according to themes

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#53]
During the harvesting, allow datasets to be automatically bound to CKAN groups according to the themes list.

**Comment by etj** [comment]
**IMPLEMENTATION**

In the configuration, we'll have a mapping between THEME codes and local Group codes, e.g.
```
   {'theme_group_mapping':  
      {
        'AGRI':['agric00','food99','campagna'], 
        'ENVI': ['ambiente','clima'] 
      } 
   }
```

**Comment by tdipisa** [comment]
The assignement to a group must be managed also during the dataset creation from GUI. So we can maintain the existing theme's  schema field managing the group assignement in background. I guess the Theme group should be automatically created in ckan if it does not exists.

**Comment by cezio** [comment]
This will probably require decoupling theme-group mapping configuration from harvester. It could be configured in UI, but to make things simpler, maybe it can be taken from configuration file? 

```
[theme_group_mapping]
AGRI = agric00
    food99
    campagna
ENVI = ambiente
   clima
  ...
```

**Comment by tdipisa** [comment]
@cezio we can probably take into account to use a proper common .py file containing the mapping. We have to discuss this together with @etj too.

**Comment by cezio** [comment]
Actually, my previous comment is with wrong question. The correct one should be: who should be able to define/change that mapping, or should changes be available immediately for usage (or can be refreshed on app restart)?

**Comment by cezio** [comment]
@tdipisa i think it's safer (and easier) to parse .ini than load arbitrary code module.

**Comment by cezio** [comment]
Anyway, parsed mapping can be persisted in db, then modification from ui could be implemented later.

**Comment by tdipisa** [comment]
@cezio yes we can use a proper .ini file too. In any case we need to review the mapping together with the client. so at the moment we can do a plan for a first skeleton with a dummy config

**Comment by tdipisa** [comment]
@cezio We don't need to manage the mapping configuration from UI, we just need a mapping config in a file to use at runtime.

**Comment by etj** [comment]
We can use a property in the production.ini file to indicate the file to use for the mapping: e.g.:
```
ckanext.dcatapit.theme_group_mapping.file = /etc/ckan/theme_group_mapping.ini
```

**Comment by etj** [comment]
The group assignment may be performed at every upsert of a dataset:
see https://github.com/geosolutions-it/ckanext-dcatapit/blob/dcatapit-1.0.0/ckanext/dcatapit/plugin.py#L235-L270

**Comment by cezio** [comment]
Implementation:
* added two models:
   `DCATAPITThemeMapFrom` (source theme) 1..n `DCATAPITGroupMapTo` (destination groups)
* added subcommand: `vocabulary import_theme_mapping PATH_TO_MAPPING`
* mapping file format:
```
 [dcatapit:theme_group_mapping]
NAME_OF_THEM = list,of,groups,
    separated by newline
    or by coma
```
* when new mapping is imported, it will clear existing groups from dataset


Code:
https://github.com/geosolutions-it/ckanext-dcatapit/compare/master...cezio:theme_to_groups_map

**Comment by cezio** [comment]
PR: https://github.com/geosolutions-it/ckanext-dcatapit/pull/70

**Comment by etj** [comment]
Agree with @tdipisa , Most of the logic is only about DB handling, which could be hard to maintain. 
Also, using a configuration file it would be more comft for admin users, since editing the file could be simply done remotely using winscp. No ssh console would be needed since the harvester process is started every 15 minutes and reloads the whole config. A single access to the file and parsing it does not use more resources than accessing the DB every time.

**Comment by cezio** [comment]
@tdipisa yes, sorry, my mistake. i preferred to have it in db at some point. fix in progress.

**Comment by etj** [comment]
WIth the mapping file set to
```
[dcatapit:theme_group_mapping]
AGRI=agri-group
ECON=econ1,econ2
EDUC=
#ENER=
```
Harvesting for instance the URL:
   http://www.mc.camcom.it/uploaded/linked-open-data/dcat-opendata-catalog.rdf

triggers this error:
```
2017-09-18 15:55:49,857 ERROR [ckan.lib.search] unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 103, in dispatch_by_operation
    index.update_dict(entity)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 103, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 258, in index_package
    pkg_dict['metadata_created'] += 'Z'
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
2017-09-18 15:55:49,857 ERROR [ckan.model.modification] unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 86, in notify
    observer.notify(entity, operation)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 129, in notify
    operation
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 103, in dispatch_by_operation
    index.update_dict(entity)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 103, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 258, in index_package
    pkg_dict['metadata_created'] += 'Z'
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

```
