### ISSUE TITLE
Handle non-conformant themes (group2theme mapping)

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#54]
Try and parse themes not included within the 13 themes thesaurus.

**Question**: *which is the field containing the theme to be parsed?*

**UPDATE** 20171031
This issue is [now](https://github.com/geosolutions-it/ckanext-dcatapit/issues/54#issuecomment-340735513) only related to map remote CKAN groups to DCATAPIT theme.

**Comment by etj** [comment]
**IMPLEMENTATION**

In the configuration, we'll have a mapping between non conformant theme keywords and conformant THEME codes, e.g.
```
   {'terms_theme_mapping':  
      {
        'agricoltura':['AGRI', 'ECON'], 
        'scuole': ['SOCI','GOVE'] 
      } 
   }
```

We may also need an information telling where the terms are coming from, i.e.
```
   {'terms_theme_mapping_source':  'dcat:keyword'}
```

**Comment by tdipisa** [comment]
Maybe could be useful to examine the current strategy used by AgID

**Comment by cezio** [comment]
seems like related to #53, but i don't think it's generic enough to reuse the code.

**Comment by cezio** [comment]
> We may also need an information telling where the terms are coming from

Could you elaborate about this a bit more? Should it be per term/theme? where it should be stored? should it be showed somehow?

**Comment by cezio** [comment]
> This is an harvesting task. Maybe could be useful to examine the current strategy used by AgID

Could you write more about this?

**Comment by tdipisa** [comment]
Dear @cezio in the current online dati.gov.it a sort of mapping is used to map the incoming themes to the 13 themes of the dcatapit profile. Below the JSON representing theis mapping:

https://www.dati.gov.it/datigov/taxonomy/synonyms/topics.json

At least we need to take into account this mapping and evaluate possible improvements if needed.

@giorgialodi can we still use this mapping as initial reference for our work or there's some other kind of specifications to discuss?

**Comment by giorgialodi** [comment]
@tdipisa yes you can. The same approach as the one adopted for the licenses.

**Comment by tdipisa** [comment]
@giorgialodi can you please highlight some relevant catalogs for this issue from the list you have previously provided and reported in the [WIKI](https://github.com/geosolutions-it/ckanext-dcatapit/wiki/Catalogs-management)?

**Comment by giorgialodi** [comment]
@tdipisa in the following, the catalogues that use different themes that are then to be mapped into the 13 ones. 
1) http://opendata.comune.bari.it/group (they have 9 groups or themes quite different from the 13 valid ones)
2) http://dati.regione.basilicata.it/catalog/group (they have 11 groups or themes, again quite different from the 13 valid ones)
3) in the case you know of Trentino (dati.trentino.it) they use 18 categories or themes and they do sometimes a kind of mapping. For instance: this dataset http://dati.trentino.it/dataset/dati-recenti-delle-stazioni-meteo is classified according to the category "Meteo" but they use the theme Environment as one of the 13 valid. This dataset: http://dati.trentino.it/dataset/bollettino-valanghe is once again classified as "Meteo" but  there is no indication of the corresponding theme of our controlled vocabulary. This entails that "Meteo" is a proprietary category (or theme) used by PAs that should be mapped into "Environment," according to our 13 themes. 
Hope this is what you asked for, and I hope it is clearer now.

**Comment by etj** [comment]
@giorgialodi some notes about that:
you are taking as example Bari and Basilicata, whereas none of them, according to the catalog list in [Catalogs management](https://github.com/geosolutions-it/ckanext-dcatapit/wiki/Catalogs-management)   are DCAT compliant.

This means that the needed functionality should be applied to the CKAN harvesting. It would add an extras field (the THEMES field handled by DCATAPIT) according to the groups in the source catalog.
We have to see if we can register a hook in the CKAN harvester to perform this processing

I see two main ways to get the source info to be bound to themes
1) groups of the dataset in the harvested catalog
2) keywords of the dataset

IMHO these are a good starting point which should include most use cases.

**Comment by etj** [comment]
@giorgialodi as a side note, I think that since we'll be modifying datasets harvested remotely, there should be a disclaimer somewhere that tells that the published datasets may be not the exact copy of the original ones.

**Comment by giorgialodi** [comment]
@etj you see the mapping as a modification of the original classification right? If so, I understand your point and yes, good suggestion. We may include in the disclaimer, that we will add to the dataportal, that we mapped the classifications offered by those PAs still not compliant with  DCAT-AP_IT  to the classifications required by the national profile.  This does not apply to PAs that already use the 13 themes. What I will probably do is to also include that mapping  in the technical guidelines for data catalogues  (https://linee-guida-cataloghi-dati-profilo-dcat-ap-it.readthedocs.io/it/latest/).

**Comment by cezio** [comment]
@giorgialodi is there a chance to get mapping file with theme codes instead of localized theme name?

**Comment by etj** [comment]
@cezio , as far as I can see, the theme code is the first string in the `syn`list:
```
"syn" : [
            "agri", <<---
            "agricoltura",
            "agricoltura-e-allevamento",
            "agricoltura-e-pesca",
...
 "syn" : [
            "econ", <<---
            "analisi economica",
            "assicurazioni",
            "attivita-produttive",
...
```

**Comment by etj** [comment]
All the listed use cases only need to map remote CKAN groups into DCATAPIT themes.
Since this is a well defined scope, we're restricting this issue (and related PRs) to that.

The new issue #75 will focus on the theme syntax fixing, but will be left in the wontfix priority, since there are no documented use cases.

**Comment by giorgialodi** [comment]
yeah, @etj is right : the code is included in the first occurence of the syn part @cezio
