### ISSUE TITLE
Improve tag validation in harvesting

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#55]
At the moment tags like 
- “controllo della qualità dell’aria” 
- “RNDT, cave dismesse, cave vuote, cave” 
- “legge 190/2012” 
- “art. 145”
are considered not valid and prevent a dataset to be harvested.

Tags should be "cleaned" somehow and imported.

- [x] CKAN harvester (https://github.com/ckan/ckanext-harvest/issues/303)
- [x] CSW harvester (https://github.com/ckan/ckanext-spatial/issues/188) [PR](https://github.com/ckan/ckanext-spatial/pull/189)
- [x] DCAT(IT) harvester (https://github.com/ckan/ckanext-dcat/issues/103) [PR](https://github.com/ckan/ckanext-dcat/pull/104)

**Comment by etj** [comment]
Some sparse notes:

- The CKAN name validator, used in the base CKAN harvester, only accepts alphanumeric chars and '-', '_'.  

- There's a `clean_tags` config option for the base CKAN harvester, which applies a replacement on a regex selection. The related logic needs some fixing however.

- Any fixes on tags handling should be also ported into `ckanext-spatial`, or at least into the CSW support extension inside the `ckanext-dcatapit` extension.

**Comment by cezio** [comment]
Do we have any data source i could test this on?

**Comment by tdipisa** [comment]
Below the piece of code in the CKAN base harvester that should manage the tag munge:

https://github.com/ckan/ckanext-harvest/blob/de01277e509a3aac279509b41fae5fe3812395d6/ckanext/harvest/harvesters/base.py#L289

For the Ckan-Ckan harvesting you can try harvest dataset from:

- http://tolomeo.provincia.fi.it/ (ckan production instance of Provincia di Firenze)
- http://cot-test.infotn.it/ (ckan test instance of Dati Trentino)
- http://dati.trentino.it/ (ckan production instance of Dati Trentino)

As mentioned by @etj any fixes should be also ported at least to the CSW spatial harvester. Below some CSW end points to use:

- http://tolomeo.provincia.fi.it/geonetwork/srv/ita/csw (geonetwork instance of Provincia di Firenze)
- http://www.territorio.provincia.tn.it/geoportlet/srv/eng/csw (geonetwork instance of Dati Trentino)

**Comment by cezio** [comment]
From what i see, `ckan.utils.munge.munge_tags` is used in `ckanext.harvest.harvesters.base.HarvesterBase._create_or_update_package()`:
https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/base.py#L289

This code is used only by `CKANHarvester` plugin implementation, in import_stage: 
https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/ckanharvester.py#L559

All other harvesters (spatial, dcat) have their own implementations of import_stage, which don't call _create_or_update_package anywhere, because they inherit from harvester's plugin base, not CKANHarvester.

IMHO,  the fix for dcat and spatial harvesters should add tags cleaning in `_get_package_dict()` in each base haverster, because it's the only common code point (technically not only, but makes most sense to add tags cleaning there). 

questions:
 * what exactly is wrong with `munge_tags` implementation? 
 * should we allow to customize invalid tags regex/replacement (if not, I guess, we should we reuse `clean_tags` config option for harvester)? 

 So far, I've implemented a fix for spatial harvester: https://github.com/ckan/ckanext-spatial/compare/master...cezio:master, i can reuse this in dcat harvesters as well

**Comment by tdipisa** [comment]
@cezio I don't remember now which exactly was the problem, I think we need to debug again.
I prefere to fix the munge_tags and try to reuse this logic in other harvester if possible (CSW harvester, RDF harvester)

**Comment by cezio** [comment]
ok, so i'll use munge_tags and see if there's a problem in implementation (i haven't seen any so far). I'll reuse `clean_tags` config option.

**Comment by cezio** [comment]
* i've simplified spatial harvester code (which is also used in dcatapit harvester):
   https://github.com/ckan/ckanext-spatial/compare/master...cezio:master

 * i've added tags filtering to dcat harvesters:
   https://github.com/ckan/ckanext-dcat/compare/master...cezio:tags_filtering

 * i've removed duplicated code in dcatapit (it's the same code that is in csw harvester):
  https://github.com/geosolutions-it/ckanext-dcatapit/compare/master...cezio:master

**Comment by cezio** [comment]
PRs:
https://github.com/geosolutions-it/ckanext-spatial/pull/1
https://github.com/geosolutions-it/ckanext-dcat/pull/1
https://github.com/geosolutions-it/ckanext-dcatapit/pull/71

**Comment by tdipisa** [comment]
Dear @cezio, I suggest some testing using the recently provided sample catalogs in the [WIKI](https://github.com/geosolutions-it/ckanext-dcatapit/wiki/Catalogs-management) (see the point 3 in the list for this issue). In general, please take into account this list during your testing for new developments

**Comment by tdipisa** [comment]
@cezio let me know about the additional testing to do as I reported above. Thank you.

**Comment by cezio** [comment]
@tdipisa i've added tests to ckanext-spatial and ckanext-dcat PRs. I had small problem with ckanext-spatial tests, because it's testsuite seems to be not working correctly. There's a lot of use of Gemini harvester, which, as I've been told, is obsolete. It doesn't implement `IHarvester` interface properly (https://github.com/ckan/ckanext-spatial/blob/50df9130cf20ef739e845f3639e2b2004c0d98e9/ckanext/spatial/harvesters/gemini.py#L48 (latest `master` commit) implements `IHarvester` interface through inheritance, but it doesn't provide `.info()` method, causing error in https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/validators.py#L116).

sample exception:
```
======================================================================
ERROR: ckanext.spatial.tests.test_harvest.TestHarvest.test_harvest_update_records
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "ckanext-spatial/ckanext/spatial/tests/test_harvest.py", line 465, in test_harvest_update_records
    source, first_job = self._create_source_and_job(source_fixture)
  File "ckanext-spatial/ckanext/spatial/tests/test_harvest.py", line 67, in _create_source_and_job
    source_dict=get_action('harvest_source_create')(context,source_fixture)
  File "ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "ckanext-harvest/ckanext/harvest/logic/action/create.py", line 72, in harvest_source_create
    source = toolkit.get_action('package_create')(context, data_dict)
  File "ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "ckan/ckan/logic/action/create.py", line 165, in package_create
    package_plugin, context, data_dict, schema, 'package_create')
  File "ckan/ckan/lib/plugins.py", line 230, in plugin_validate
    return toolkit.navl_validate(data_dict, schema, context)
  File "ckan/ckan/lib/navl/dictization_functions.py", line 238, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "ckan/ckan/lib/navl/dictization_functions.py", line 299, in _validate
    convert(converter, key, converted_data, errors, context)
  File "ckan/ckan/lib/navl/dictization_functions.py", line 204, in convert
    value = converter(converted_data.get(key), context)
  File "ckanext-harvest/ckanext/harvest/logic/validators.py", line 118, in harvest_source_type_exists
    info = harvester.info()
AttributeError: 'GeminiHarvester' object has no attribute 'info'
```
Besides that, harvest job config used in configs is missing owner info:
```
======================================================================
ERROR: ckanext.spatial.tests.test_harvest.TestHarvest.test_harvest_update_records
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "ckanext-spatial/ckanext/spatial/tests/test_harvest.py", line 465, in test_harvest_update_records
    source, first_job = self._create_source_and_job(source_fixture)
  File "ckanext-spatial/ckanext/spatial/tests/test_harvest.py", line 67, in _create_source_and_job
    source_dict=get_action('harvest_source_create')(context,source_fixture)
  File "ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "ckanext-harvest/ckanext/harvest/logic/action/create.py", line 72, in harvest_source_create
    source = toolkit.get_action('package_create')(context, data_dict)
  File "ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "ckan/ckan/logic/action/create.py", line 172, in package_create
    raise ValidationError(errors)
ValidationError: None - {'owner_org': [u'A organization must be supplied', u'Missing value']}
```

I've added a workaround (with dummy `.info()` method and owner object), so this specific test case should work, when running 
> nosetests -s --ckan --with-pylons=path/to/test.ini ckanext.spatial.tests.test_harvest:TestHarvest.test_clean_tags

**Comment by etj** [comment]
If we have to create a PR on to the official ckanext-spatial, an issue on that repo should be opened.
I tried running the tests on the official master branch, to describe the encountered error, but I didnt find any, and the tests run and pass properly.
Pls also note that the latest commit at the moment is [this one](https://github.com/ckan/ckanext-spatial/commit/f805d412d1c3c0db1b552f5215ba279292b7cfa8):
```
commit f805d412d1c3c0db1b552f5215ba279292b7cfa8
Author: amercader <amercadero@gmail.com>
Date:   Thu Sep 14 15:58:18 2017 +0100

    Fix travis service name
```

Please re-check your commits on ckanext-spatial, since they can be made against an old version.

**Comment by cezio** [comment]
yes, this probably was because of my local configuration (i've used separate ini for tests, which was based on dev, which included additional plugins). With plain tests.ini (just modifications for db location) it works fine. I've remove that hack for `IHarvester.info()`.

**Comment by etj** [comment]
CSW sources providing bad chars in keywords seems to be harvested without any problems also by the unfixed official spatial harvester.
Harvesting an ISO19139 metadata containing this keyword
```
  <gmd:keyword>
     <gco:CharacterString>this is a bad keyword!!-_ %à*$/'`^°?!</gco:CharacterString>
  </gmd:keyword>
```
that's what I get in the harvested dataset:
![image](https://user-images.githubusercontent.com/717359/32442260-1009521a-c2fb-11e7-9f3d-99089797b0cf.png)

**Comment by etj** [comment]
This issue explains the error when fixing tags in CKAN harvester:
   https://github.com/ckan/ckanext-harvest/issues/303

**Comment by etj** [comment]
Added a PR to the official ckanext-harvest repo:
    https://github.com/ckan/ckanext-harvest/pull/304

**Comment by cezio** [comment]
there's pr with fixes for ckanext-dcat review comments: https://github.com/geosolutions-it/ckanext-dcat/pull/6

**Comment by simboss** [comment]
@etj can we give a kick to the community about this?

**Comment by cezio** [comment]
Fix for review from upstream: https://github.com/geosolutions-it/ckanext-spatial/pull/8

Travis fails (https://travis-ci.org/cezio/ckanext-spatial/builds/373837595), but it's not related directly with my code. Upstream seems to be affected by similar problem: https://travis-ci.org/ckan/ckanext-spatial/builds/372035227
