### ISSUE TITLE
Licence: vocabulary

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#56]
Investigate how the licence classification made by AgID can be used as vocabulary.

Note that the DCATAPIT extension provides a line command in order to load vocabs into the DB. It could be extended in order to handle the licence vocabulary as well.

Probably the licence vocabulary will need some more fields (a new DB table?) in order to store all of the info about licences.

**Comment by tdipisa** [comment]
The licenses vocabulary to use is available at the  URL below in various format:

https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/Licenze

**Comment by cezio** [comment]
i've reviewed other issues. We could store additional license data in separate table, but do we need full structure of license description? It looks like at the moment, we need:
 * name
 * url (used in license mapping)
 * version (used in #58)
 * type (also in #58)
 
all the rest we could store serialized.

**Comment by etj** [comment]
DCATAPIT requires:

| AP| prop name | card |type| domain | description|
|----|---|---|---|---|---|
|DCAT| type | 0..1  | dct:type | URI|license type, e.g. "public domain", "fee required",... Use the concept URI in http://purl.org/adms/licencetype/
|DCATAPIT|name|0..n|foaf:name|rdfs:literal|License name. Use the `identifier`from the vocabulary.
|DCATAPIT|version|0..1|owl:versionInfo|rdfs:Literal|

**Comment by etj** [comment]
This is one sample entry from [Licenze.rdf](https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/Licenze/Licenze.rdf)
``` 
 <rdf:Description rdf:about="http://dati.gov.it/onto/controlledvocabulary/License/A11_CCO10">
    <owl:versionInfo>1.0</owl:versionInfo>
    <dct:type rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A1_PublicDomain"/>
    <foaf:name xml:lang="en">Creative Commons CC0 1.0 Universal - Public Domain Dedication (CC0 1.0)</foaf:name>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <skos:inScheme rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License"/>
    <skos:prefLabel xml:lang="en">Creative Commons CC0 1.0 Universal - Public Domain Dedication (CC0 1.0)</skos:prefLabel>
    <skos:broaderTransitive rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A_OpenLicense"/>
    <dcatapit:referenceDoc rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://creativecommons.org/publicdomain/zero/1.0/</dcatapit:referenceDoc>
    <skos:prefLabel xml:lang="it">Creative Commons CC0 1.0 Universale - Public Domain Dedication (CC0 1.0)</skos:prefLabel>
    <rdf:type rdf:resource="http://purl.org/dc/terms/LicenseDocument"/>
    <clvapit:hasRankOrder>3</clvapit:hasRankOrder>
    <skos:notation>A.1.1</skos:notation>
    <skos:broader rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A1_PublicDomain"/>
    <foaf:name xml:lang="it">Creative Commons CC0 1.0 Universale - Public Domain Dedication (CC0 1.0)</foaf:name>
    <dct:identifier>A.1.1</dct:identifier>
</rdf:Description>
```

**Comment by etj** [comment]
Further info on model are in the model issue: https://github.com/geosolutions-it/ckanext-dcatapit/issues/65#issuecomment-341401215
