### ISSUE TITLE
Licence: mapping

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#57]
Map the licences defined by the Public Organizations into the vocabulary. 
E.g.: if a PA uses a licence CC-BY-NC, this should be defined as

- non open licence 
  - non commercial 
    - CC-BY-NC

Needed changes:
- DCATAPIT harvester: map value from `dct:license/foaf:name`
- DCATAPIT CSW support: map value from a configured XPATH
- CKAN harvester: extend harvester in order to use a configuration mapping

**Comment by tdipisa** [comment]
Dear @cezio in the current online dati.gov.it a sort of mapping is used to map the incoming licenses to the ones of the dcatapit vocabulary. Below the JSON representing this mapping:

https://www.dati.gov.it/datigov/taxonomy/synonyms/licenses.json

At least we need to take into account this mapping and evaluate possible improvements if needed.

@giorgialodi can we still use this mapping as initial reference for our work or there's some other kind of specifications to discuss?

**Comment by giorgialodi** [comment]
@tdipisa yes you can.  At the time being it is the only working mapping that we have. The reference controlled vocabulary for Licences is the [following](https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/Licenze/Licenze.ttl) (which is also available in other formats if required). If you think improvements of the JSON mapping are required for a better mapping between current PAs' data and the controlled vocabulary above, feel free to suggest them.

**Comment by cezio** [comment]
> CKAN harvester: extend harvester in order to use a configuration mapping

Could you elaborate a bit about this scenario? I'm not sure if I understand this correctly - does it mean, when doing ckan-ckan harvesting, shouldn't we copy license information from resource (or apply it from dataset if per-resource is not available)? should this be processed additionally in harvester?

**Comment by cezio** [comment]
For the record:

> Map the licences defined by the Public Organizations into the vocabulary.
E.g.: if a PA uses a licence CC-BY-NC, this should be defined as
> * non open licence
>    * non commercial
>        * CC-BY-NC

is implemented in https://github.com/geosolutions-it/ckanext-dcatapit/issues/65

**Comment by cezio** [comment]
> DCATAPIT CSW support: map value from a configured XPATH

Should this be defined in harvester's config? Any default value?

**Comment by cezio** [comment]
btw, there's https://github.com/ckan/ckan/blob/master/ckan/model/license.py, which is applied to Dataset Shouldn't this be somehow included in mapping?

**Comment by cezio** [comment]
This is how I see this issue:

 * CKAN harvester
   I see several scenarios here:
    * when license information will be exposed as resource's extra, do probably don't need to do anything here. It should be transfered in ckan-ckan harvesting without modification. Or, do we want to process it somehow (like adjusting license if source uses old/different license vocabulary)?
    * when license information is not available for resource, should we:
       * copy it from dataset? 
       * use harvester's config to provide a default value?

 * DCATAPIT CSW support: map value from a configured XPATH

   Do we need to use xpath here? It looks like csw harvester handles this in different way:
   https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/base.py#L291

   This is similar situation as in CKAN harvester, where we have dataset license only. 
 
 * DCATAPIT harvester: map value from dct:license/foaf:name

   When resource's license is exposed, this should be copied to target resource. If not, again, this is similar situation as above, where we probably want to transfer license information from dataset to resource.

If we want to copy license information from dataset to resource, I wonder do we need to do this at harvester's level (three different harvesters modifications, which will do exactly the same thing)? I'd say it's better to do this in `IResourceController.after_create/.after_update`.

How should we handle situation when dataset's license cannot be mapped to resource's license? Log error, and move along?

This could be a case when harvesting, because external catalogs may have different licenses applied to datasets.

**Comment by etj** [comment]
Recap:
- [ ] CKAN harvester:
  - license in resources' extra: 
    - if it exists, perform simple validation. If not valid, replace with the [unknown license type](https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/Licenze/Licenze.ttl#L153-L163)
    - if it does not exist, try to map the dataset's license to a license in the controlled voc
    - fallback to the unknown license type
- [ ] CSW
   - Some catalogs reference the CC licenses in the `LegalConstraints/useLimitation` elements, while others may use the `otherConstraints` field. Since this location is defined at catalog level, it should be made configurable at harvester's level if possible.
The value should be extracted via xpath, heuristically mapped to a known license, and then reported into every resource in the dataset.
- [ ] DCATAPIT harvester
  - If resource exposes the license, copy it, otherwise use the unknown license type.
  - Dataset license is not available for DCAT, so we should make some inferences here:
    - if all licenses are the same, copy it right away into the dataset (mapping with the available ones)
    - if resources' licenses differ we'll have to decide if we want the most open or the most closed one, among the ones bound to the resources. This also mean we'd need a kind of *openness* index associated to each license. If we don't have this, we can just take an arbitrary license among the ones in the dataset's resources. 
    Probably we need also an opinion from @giorgialodi here.

**Comment by cezio** [comment]
Thx, @etj. can those modifications for  CSW/CKAN harvesters be implemented in DCATAPIT's harvesters from https://github.com/geosolutions-it/ckanext-dcatapit/tree/master/ckanext/dcatapit/harvesters ?

**Comment by etj** [comment]
@cezio for CSW and CKAN harvesters we are already doing values replacement in the dataset according to the harvested data, so that's exactly the place where to put the implementation.

**Comment by cezio** [comment]
> Some catalogs reference the CC licenses in the LegalConstraints/useLimitation elements, while others may use the otherConstraints field. Since this location is defined at catalog level, it should be made configurable at harvester's level if possible.

Should I use `ISOKeyword`/`ISOElement` to search for that? What namespace those elements use?

**Comment by giorgialodi** [comment]
@etj I read your comment. If we cannot determine the license it is a good idea to use "unknown licence type" or, alternatively, we can assume the open data by default principle that is "CC BY v. 4.0" as stated in the national technical guidelines (this is reasonable when we harvest from catalogues that are named as "open data catalogues"). However, please note that license is an element bound to the Distribution (resource) of the Dataset and not to the Dataset itself. Said in another way, it may happen that more distributions of the same dataset expose different licenses. In essense, we do not need to link the license to the dataset.

**Comment by etj** [comment]
@cezio those ISOElements definitions should take in consideration all the known cases, so they should already be fine.

**Comment by cezio** [comment]
> CKAN harvester:

 added validation of license. if it's not valid, unknown will be used

>  CSW

It looks like there's already some code that adds license to resources in other fields, but i've added mapping code and tested on local csw source.

>  DCATAPIT harvester

This is also implemented, both for rdf parser and serializer, tests in suite
