### ISSUE TITLE
Improvement for otherIdentifier: cardinality

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#60]
Support 0..n cardinality.

**Comment by cezio** [comment]
it's supported in ckanext-dcat : 
 * https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/profiles.py#L926
 * https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/profiles.py#L732

Additional support for list in parsing: https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/dcat/profiles.py#L115

there's schema field in dcatapit: https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/schema.py#L100-L108

**Comment by cezio** [comment]
I've implemented similar solution as in #59:
* identifiers are stored as json in extra field `alternate_identifier`
* there's edit form with multiple elements allowed:

![image](https://user-images.githubusercontent.com/116021/33278388-b7c5a11a-d39b-11e7-9e9b-71e73c92c104.png)

* identifiers are rendered in read view as:

![image](https://user-images.githubusercontent.com/116021/33278460-e835534a-d39b-11e7-8987-c73ef8efd9b0.png)
