### ISSUE TITLE
Improvement for temporal coverage: cardinality

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#61]
Support 0..n cardinality.

A new extras field is needed to support a list of begin/end couples.
Original fields `temporal_start` and `temporal_end` shall be kept for compatibility with the base DCATAP profile; values will be populated with the mininum of the begin value in the couples list, and with the maximum of the end value in the couples list.

**Comment by cezio** [comment]
This can be implemented in similar way as #59, #60 and #62. I'll store jsonified data to `temporal_coverage` field.
