### ISSUE TITLE
Improvement for dct:creator: cardinality

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#62]
Support 0..n cardinality.

**Comment by cezio** [comment]
some support in parser: https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/dcat/profiles.py#L212-L221

and serializer https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/dcat/profiles.py#L473

**Comment by cezio** [comment]
rigth now, this is creator field: ![image](https://user-images.githubusercontent.com/116021/32940750-d462c00c-cb83-11e7-9812-2a147fb7011e.png)

So, this should be not required, but user should also be able to add additional records here. If this is desired ui behavior, then I'll have to modify rdf processors to supports ..n part

**Comment by cezio** [comment]
for the record, I'll add this in similar way as #60 and #59: json with list of creators, and dynamic ui elements.

**Comment by cezio** [comment]
This is a part of https://github.com/geosolutions-it/ckanext-dcatapit/pull/93 due to shared ui code

**Comment by cezio** [comment]
Multiple creators are displayed in dataset view:

![image](https://user-images.githubusercontent.com/116021/33379733-2f92926a-d519-11e7-8e43-0ff523d3d43d.png)

and handled in edit form:

![image](https://user-images.githubusercontent.com/116021/33379798-58f4abd4-d519-11e7-94af-9cef6613543d.png)

Internally, it's jsonified list as `creator` extra field:
```
[{'creator_name': 'abc', 'creator_identifier': "ABC"},
{'creator_name': 'cde', 'creator_identifier': "CDE"},]
```

RDF processors will handle old version and merge it with `creator` list.
