### ISSUE TITLE
Improvement for dcatapit:Agent: multilang

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#64]
Review model, harvesting and serialization of 
- `dct:publisher`
- `dct:rightsHolder`
- `dct:creator`

**Comment by cezio** [comment]
* dct:publisher
 
 Added support in serializer and parser, tests updated. 

* dct:rightsHolder
 
 This was supported already, but no tests were added for multilang

* dct:creator

 This is supported already in #62
