### ISSUE TITLE
Licence: model

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#65]
Tasks:
- [x] implement model classes for license vocabulary
- [x] script for importing license vocabulary

--- 
DCATAPIT specs about license info are:
- `dct:type` 0..1
- `foaf:name` 0..N
- `owl:versionInfo` 0..1

These properties will be populated using the vocabulary handled in #56.

**Comment by cezio** [comment]
what should be value for `dct:type`?   `<rdf:type rdf:resource="http://purl.org/dc/terms/LicenseDocument"/>`?

**Comment by tdipisa** [comment]
@cezio, [here](https://www.dati.gov.it/sites/default/files/DCAT-AP_IT_v10.pdf) the dcatapit specs (in italian) containing some examples. @etj can clarify some implementation's details.

**Comment by giorgialodi** [comment]
The license vocabulary we created works as follows. If there is a license, say CC BY, its type is defined as the second level of the hierarchy of the taxonomy we created. The second level identifies the types of licenses. In this example, CC BY is of type "A2_Attribution" that is exactMatch with (semantically equivalent to)  http://purl.org/adms/licencetype/Attribution (this latter is the controlled vocabulary of the DCAT-AP at the European Level). In this way we are compliant with the rules at the European level but we can manage all these things for the licenses using the taxonomy we created.

**Comment by etj** [comment]
`dct:type[0..1]` should contain the URI reported in http://purl.org/adms/licencetype/.
Those URIs are the one reported in the `exactMatch` element of the 2nd level licenses in the [Italian license document](https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/Licenze/Licenze.rdf).
This means that the resource can contain a reference to 2nd or 3rd level licenses to be compatible to the EU profile (since we can resolve the parent level of a 3rd level licence). 

In the GUI, when setting a resource license, we'll want to present a license tree, were only the 2nd and 3rd level entries will be selectable.

The internal licence vocabulary should store:
- `adms_type`: [0..1]: URI in the ADMS vocabulary
   -  1st level licences: null
   -  2nd level licences: `exactMatch`
   - 3rd level licences: `exactMatch`of parent license
- `version`: [0..1]: only specified as `owl:versionInfo`in 3rd level licenses
- `uri`: [1]: URI in DCATAPIT vocabulary (the `Description`'s `rdf:about`)
- `rankOrder`[1]: used for creating the tree on the GUI

As for multilang, we need another table to store the localized label:
- `fk_id`
- `lang`
- `label`

We'll use the label both in the GUI and in the RDF output.

**Comment by cezio** [comment]
> As for multilang, we need another table to store the localized label:

 I was thinking how to implement this. Do we need multilang here? all we need is to translate name for one field in extra (and this field won't even be saved in translated form) and add field for creation form with localized options. So, my idea would be to add hooks with `IResourceController.before_view()`, modify `license` field. I'm not sure how to patch resource schema to have license field added as a select.

**Comment by etj** [comment]
Short answer: yes, we need multilang.

Long one:
Let's say we have the GUI in German (some PA in Italy may require it). 
When creating a dataset, we need to show in the edit page the widget showing the available licenses in the DE language. 
It means we need to store the License label in IT, DE and probably FR as well.

**Comment by cezio** [comment]
Model is done, it's inited along with other tables when `vocabulary initdb` is called. 

Licenses can be populated with `vocabulary load --name=licenses --filename=..`

I've added current `extra/license.rdf` to repo, it's used by tests. Readme is also updated with information about data population.
