### ISSUE TITLE
GUI: add user help for each field

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#66]
For each DCATAPIT field in the edit form, add a info icon, which will open a popup with a localized description of the field.

**Comment by marcomb** [comment]
We are refining a short vademecum (in the form of a google sheet) that explain in italian how to fill the metadata, field by field. So maybe could be used (after a review) for build this online help 

https://docs.google.com/spreadsheets/d/1ZxNByhvoEGot6oQ7vr9ZcLDA2jZyBZfQZTKdl4h06n0

**Comment by cezio** [comment]
* help items are in `ckanext.dcatapit.schema` items as `help` keys
* forms are created with dcatapit's specific macros which support `help` argument, which will create info icon with tooltip, if help contents are provided

**Comment by etj** [comment]
Pls remove the full text from schema.py, and use placeholders instead, so that all the localized stuff is in the .po files.
We may use something like:
```
 'help': _("theme_help_placeholder")
```
in schema.py

**Comment by cezio** [comment]
should i also move used help texts to po?
