### ISSUE TITLE
Editing GUI refactorization: step-by-step input

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#67]
Split the editing GUI in a step by step flow, so that only fields related to a certain topic will be visible at each step. 
There can be a tabbed structture (a tab for each step) and a final tab for validation and saving.

This structure can be used as a reference:
   http://guidance.data.gov.uk/dataset_form.html

**Comment by marcomb** [comment]
The actual implementation doesn't allow to set the field order in the form. Expecially in EDIT mode the list of Fields (each one a metadata) is not very logical for a data/metadata editor. We grouped the fields in a more logical way in the compilation guide (text to describe the dataset, then time information, then geographical information, then editors/publishers informations). Could be implemented also in real form? 
[https://docs.google.com/spreadsheets/d/1ZxNByhvoEGot6oQ7vr9ZcLDA2jZyBZfQZTKdl4h06n0]
link to the metadata compilation guide

**Comment by etj** [comment]
https://docs.google.com/drawings/d/1qcH9CNgnamzY4LE5ipUS5sUoSZNDu4lO_NelChmsUwQ/edit?usp=sharing

**Comment by cezio** [comment]
Thanks for the mockup. However, how should extra fields and non-extra fields, that are not covered by this selection, be grouped?

**Comment by etj** [comment]
All tabs contain the extra fields:

![ckan99](https://user-images.githubusercontent.com/717359/37026399-9a463ff6-212e-11e8-9ee3-381363383485.png)

**Comment by etj** [comment]
Style for geonames dropdown seems broken


![ckan100](https://user-images.githubusercontent.com/717359/37026595-2cc70112-212f-11e8-921c-700d9cc1e626.png)

**Comment by cezio** [comment]
All extras should be in extras tab.

I've improved autocomplete style:

![image](https://user-images.githubusercontent.com/116021/37542501-af97f0c4-295e-11e8-8484-d28b1b8e41eb.png)
