### ISSUE TITLE
Improvement for dct:location (Geographical Coverage)

### ISSUE THREAD

**Issue by marcomb** [geosolutions-it/ckanext-dcatapit#69]
Inclusion of Provinces, Regions and "Italy" in the section on the choice of geographical coverage. 

This ha sto be agreed with AgID because it is an improvement of DCATAPIT. Maybe @giorgialodi could express her opinion about it.

It would be desirable to combine the current alphanumeric choice (eg "Bolzano") with the a subset or a unique Geonames URL (eg http://www.geonames.org/3181912) in order to have only one element to handle while filling the metadata. 
The EU MDR vocabulary is very poor, with few geographical locations, 
http://publications.europa.eu/mdr/resource/authority/place/html/places-A.html

It could be implemented using the geonames.org web API and get the genames URI in a semi-automated way.

**Comment by giorgialodi** [comment]
@marcomb the specifications of GeoDCAT-AP, which are used for the management of the geospatial component of the current DCAT-AP_IT, already say that when a place cannot be found in the suggested controlled vocabulary (the one from the MDR metadata Registry of the Publication Office), geonames can be used instead. If you see in the examples provided in the guidelines, we already use geonames for more specific places of our territory. There can be an alternative solution as well I have in mind but I need to check it carefully.

**Comment by tdipisa** [comment]
solved with #123
