### ISSUE TITLE
Handle source Organizations

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#72]
The CKAN harvester has an option like this:

> `remote_orgs`: By default, remote organizations are ignored. Setting this property enables the harvester to import remote organizations. There are two alternatives. Setting it to `only_local` will just import organizations which id is already present in the local CKAN. Setting it to `create` will make an attempt to create the organizations by copying the details from the remote CKAN.

We are already placing original Organization info in the RDF information as pointOfContact information (https://github.com/geosolutions-it/ckanext-dcatapit/blob/dcatapit-1.0.0/ckanext/dcatapit/dcat/profiles.py#L473-L527).

We may introduce the same option `remote_orgs` with the same allowed values `only_local` and `create` in the DCATAPIT harvester as well.

**Comment by giorgialodi** [comment]
just a small comment on this: in the profile we may distinguish between the catalogue (we are already dealing with it) and the organizatios. The organizations can be maintained using the the rights holder element of the DCAT-AP_IT profile.. In the pointOfContact  we have single offices of the organizations, at least following the DCAT-AP_IT specifications. Hope this clarifies

**Comment by marcomb** [comment]
about this issue, I am not convinced that it is correct as it is now implemented.
So maybe could be better, as @giorgialodi suggest, to get it (ContactPoint) from the Rights Holder (that is inserted in the dataset metadata form) of the DCAT-AP_IT profile. The source organization is in most of the cases not the PointOfContact of the dataset. 

Moreover there is a field in the CKAN metadata form named "Contact" (free text, typically an email address of a specific person/office that must be contact to ask about the dataset) and this value it is NOT used in the DCAT_AP_IT dataset profile (what you could see when you type ".jsonld" in a dataset URL.
 
A possible alternative solution is to take the "Contact" value inserted in the dataset and add it with the Source Organization information, complementing it inside the DCAT-AP-IT profile, enriching it with a more specific contact information (and use a value inserted by the Editors that is not used as it is now by the DCAT-AP_IT profile)

**Comment by cezio** [comment]
@giorgialodi so, it seems that `rigthtsHolder` could be used to propagate source organization. However, we probably should remove this field from schema and metadata form, because it will clash with above implementation scenario.

**Comment by giorgialodi** [comment]
@cezio what you mean exactly with "we probably should remove this field from schema and metadata form"? rightsHolder is one of the main extension introduced in the DCAT-AP_IT profile since this concept is clearly included in the Italian Law. RightHolders, Publishers and Creators are important roles of the organizations on the datasets, and they may not coincide (there are cases in which they are three separate organizations). The ContactPoint for the dataset can be typically an office of the rightsHolder organization but there may exist cases in which this is not true and the contact point may be an office of the publisher or of a third party.  So not sure what you are proposing here :)

**Comment by cezio** [comment]
Sorry, I may formulated this in wrong way. 

From discussion above and talk with @etj  I understood and exchange of Organization data with RDF should utilize `rightsHolder` element. So, when `remote_org` flag is set to `create`, harvesting node should use `rightsHolder` to populate Organization. This means also, there can be a integrity conflict, because we handle rights holder in edit form, and, if present (and it's required, so it will always be filled), can carry different data than Organization associated with dataset. So, my idea is to remove this field from form (not from schema, of course).

**Comment by etj** [comment]
I guess @Cezio comment was not clear enough.

The rightsHolder info should stay in the schema, bc, as Giorgia said, it's part of the specification.
The idea is to only remove that fields from the editing form, since that information will be taken from the owner (CKAN's) Organization.

So, when a dataset is created in the editor form, the extra fields containing rightsHolder info will be left blank.
When the dataset is serialized to RDF, it will fill in rightsHolder info from the owner organization, if the related extra fields in the dataset do not exist. If the extra fields exist, they will be serialized as is, without reading anything about the owning organization. This will preserve the original rightsHolder in transitive harvesting.

Furthermore, by enabling a proper option, when harvesting remote datasets through the DCAT protocol, it will be possibile to create the organization locally. This option will not change anyway the behaviour of the assignment to the extra fields in the dataset.

**Comment by etj** [comment]
On a second thought, we may want to assign the rightsHolder info (read from the organization) when saving the dataset from the editing form. This will allow CKAN harvesters to get the proper information in the extra fields.

**Comment by cezio** [comment]
Besides implementation above, i've changed the way rights holder fields in edit form are displayed now. They are disabled, and if dataset doesn't have rights holder data, they will be populated with organization's data:

![image](https://user-images.githubusercontent.com/116021/34170978-180b2a38-e4ed-11e7-8daf-b0e6909ba6a3.png)

Organization form now has IPA/IVA field:
![image](https://user-images.githubusercontent.com/116021/34171061-546d6946-e4ed-11e7-9d2f-ee0a7abb0806.png)

 It's not required at the moment, so datasets without rights holder may have organizations assigned without identifier as well. Should we prevent such situation somehow?

**Comment by giorgialodi** [comment]
aaah, ok probably I have understood :-)  and it seems ok what you wrote @etj . Obviously, every information that you can get from other data you fill in in other forms (or that you can infere from either the login information --> I log in to the system, I am an employee associated with an organization or from the owner of the platform itself) can be used to fill in automatically these fields (users may want anyway to change them). The identifier for the Agent (which is the organization that can be, among others, the rightholder) is mandatory in the metadata profile.

**Comment by cezio** [comment]
Actually, i had to remove input fields and use plain text, because fields will be submitted and holder information will be saved with dataset every time.

![image](https://user-images.githubusercontent.com/116021/34200128-3b5c65b4-e570-11e7-8082-5b045bcb292c.png)
