### ISSUE TITLE
Missed self reference in do_load() function

### ISSUE THREAD

**Issue by ranierigmusella** [geosolutions-it/ckanext-dcatapit#82]
I have noticed that the function has missed a reference to self. This causes an error during the call of:

` paster --plugin=ckanext-dcatapit vocabulary load --url http://publications.europa.eu/mdr/resource/authority/language/skos/languages-skos.rdf --name languages --config=/etc/ckan/default/production.ini`

A possible solution could be:

`do_load(self, vocab_name, url=url, filename=filename)`

`def do_load(self, vocab_name, url=None, filename=None):`

Best regards
Giuseppe Ranieri Musella

**Comment by etj** [comment]
@ranierigmusella error not replicable at the moment. Please paste any stacktrace you have about this error.

**Comment by ranierigmusella** [comment]
Hello etj, 
at the time I've downloaded the exstension, the code had the commit n. 9734fac. Now, as I can see, you have already resolved the issue in the newer commit :) You can close it. 

Best regards
Giuseppe Ranieri Musella

**Comment by etj** [comment]
Ok, cool. Thanks for the feedback :)
