### ISSUE TITLE
Index datasets by Italian region

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#87]
- [x] add a region field in organization
- [x] index dataset by the owner organiztion region
- [x] add region faceting

**Comment by cezio** [comment]
Do we need vocabulary here? It seems so. Do we have any good source for that? And what about multilang versions?

**Comment by etj** [comment]
@giorgialodi is there already a vocabulary with Italian Regions and related codes?

**Comment by giorgialodi** [comment]
yep but it is unstable at the moment. Take a look at this: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/ClassificazioneTerritorio  I have to transform it into JSON-LD as well (but it takes me just a few seconds!). It may be subject to changes over the next months. It comes from ISTAT's territorial classification and together with ISTAT we are working on it and on the related ontology (of locations and addresses). Therefore, we could use it but we need to pay attention to use it in a way that, if it changes, this has a small impact on our development.

**Comment by cezio** [comment]
@giorgialodi could you provide rdf as well? If data structure won't change (or won't change much), i think this can be used as temporary source.

**Comment by cezio** [comment]
Should this be multilingual like the rest?

**Comment by giorgialodi** [comment]
@cezio  do you mean in RDF(XML? Because there is the RDF/turtle serialization available. I am trying to automatically convert the RDF/turtle in RDF(XML and in JSON-LD but at the moment due translators failed (probably because the file is quite big). I am trying with Protegé and see if the result is ok. Let me which RDF serialization you prefer!

**Comment by giorgialodi** [comment]
BTW: the names should be multilingual I guess, but I do not think we have the multilinguism for that classification :-( I may ask to ISTAT which is the owner of the classification. I will let you know. Probably we may  think to have the multilinguism for the names even if, at the time being, we have just the Italian version

**Comment by cezio** [comment]
Actually, I can parse RDF/turtle as well, so RDF/xml won't be needed.

**Comment by etj** [comment]
Pls note that we only need the `clvapit:Region` nodes from [the RDF file](https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/VocabolariControllati/ClassificazioneTerritorio/Istat-Classificazione-08-Territorio.ttl).

**Comment by giorgialodi** [comment]
ok guys, probably I also have the RDF/XML. In any case, I can publish it on github, as we did for  other controlled vocabularies (the JSON-LD produced by protegé has some issues, from my point of view).

**Comment by etj** [comment]
Recap on assigning Regions to a dataset.

When creating an Organization, the admin will be able to assign one Region to it.

When editing a dataset, you'll have to assign an Organization to the dataset, so the dataset will be assigned the Region of its belonging Organization.

When creating/editing an harvester, the admin needs to assign an organization to it.
All the datasets imported by that harvester will be assigned the Region of the Organization of the harvester.

In case the harvester is creating its own organizations (geosolutions-it/ckanext-dcatapit#72), since the Region is not defined within the Organization RDF node, the brand new Org will not have a Region associated to it, and all imported datasets will not have a Region associated. 
The admin shall edit the brand new organization, by adding the Region info. Next harvesting runs will set/update the Region info in the dataset.

**Comment by giorgialodi** [comment]
Do you want to do this for the additional filter that distinguishes datasets according to regions? Because it may happen that the spatial coverage of the dataset can be cross-region and not 1-1 with the Region of the Organization. In addition, in case of Central Public Administrations the region is Lazio?

**Comment by cezio** [comment]
Organization now has `region` field:
![image](https://user-images.githubusercontent.com/116021/34261719-62fd69ce-e66a-11e7-9658-4e1458881e83.png)

However, during vocabulary import, tag values are normalized (no non-ascii chars, lowercase etc).

Datasets can be search with org's region as a facet:
![image](https://user-images.githubusercontent.com/116021/34261663-35b60b38-e66a-11e7-9591-c88c297dcb5d.png)

It's indexed with `organization_region` field in solr

**Comment by cezio** [comment]
> However, during vocabulary import, tag values are normalized (no non-ascii chars, lowercase etc).

This is actually wrong. Vocabulary import creates localized entries, but they are shown only when proper locales are used by client.

**Comment by cezio** [comment]
Facets support requires enabling `dcatatpit_subcatalog_facets` plugin. I think we could rename this to `dcatapit_facets`, since it's more general now.
