### ISSUE TITLE
Summary of catalogs harvesting

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#88]
Add a page presenting the list of harvester, 
- Title
- Harvesting URL endpoint
- Number of harvested datasets
- Timestamp of latest harvesting run
- Timestamp of next scheduled harvesting run (opt)

e.g. https://www.dati.gov.it/elenco-harvest-sources

**Comment by cezio** [comment]
Under which url should it be visible? `/harvest`? Should it also be linked somehow from home page or admin part?

**Comment by cezio** [comment]
Should this be implemented in ckanext-harvest or ckanext-dcatapit?

**Comment by etj** [comment]
This is a GUI customization requested by AgID. Even if this may be of public interest, and all the required info are provided by the schema modifications provided by ckanext-harvest, it would take too long to have it merged into the official ckanext-harvest, so let's implement it into ckanext-dcatapit.
Also, since some organization implementing dcatapit could not be interested in such a page, it hsould be implemented in a standalone plugin contained into the ckanext-dcatapit extension.

**Comment by cezio** [comment]
I've added following table:

![image](https://user-images.githubusercontent.com/116021/34305524-c699658a-e73e-11e7-93a0-2a6db4acdcde.png)

It requires enabling `dcatapit_harvest_list` plugin.

**Comment by etj** [comment]
"Next scheduled harvest run" prints {{ hs.status.next_harvest }}{{ hs.status.next_harvest }}.
In ckanext-harvest:
```
    if next_job:
        out['next_harvest'] = 'Scheduled'
    else:
        out['next_harvest'] = 'Not yet scheduled'
```
It would  be more useful the show harvesting frequency.

- [ ] "Next scheduled harvest run" -> "Update frequency"
- [ ] Improve "last harvest run"  formatting as "yyyy-mm-dd hh:MM"
